"use strict";
TAESF.NTTC.Workflow = (() => {
  const S = TAESF.NTTC.Constants.STATUS;
  const transitions = Object.freeze({
    [S.DRAFT]:[S.READY_FOR_ONLINE_SUBMISSION], [S.READY_FOR_ONLINE_SUBMISSION]:[S.SUBMITTED_FOR_INITIAL_REVIEW],
    [S.SUBMITTED_FOR_INITIAL_REVIEW]:[S.UNDER_INITIAL_REVIEW], [S.UNDER_INITIAL_REVIEW]:[S.WITH_DEFICIENCY,S.APPROVED_FOR_HARDCOPY_SUBMISSION],
    [S.WITH_DEFICIENCY]:[S.COMPLIANCE_SUBMITTED], [S.COMPLIANCE_SUBMITTED]:[S.UNDER_RE_REVIEW],
    [S.UNDER_RE_REVIEW]:[S.WITH_DEFICIENCY,S.APPROVED_FOR_HARDCOPY_SUBMISSION],
    [S.APPROVED_FOR_HARDCOPY_SUBMISSION]:[S.SUBMISSION_SCHEDULED], [S.SUBMISSION_SCHEDULED]:[S.APPOINTMENT_CONFIRMED,S.APPLICANT_ARRIVED],
    [S.APPOINTMENT_CONFIRMED]:[S.APPLICANT_ARRIVED], [S.APPLICANT_ARRIVED]:[S.HARDCOPY_UNDER_VERIFICATION],
    [S.HARDCOPY_UNDER_VERIFICATION]:[S.HARDCOPY_RECEIVED,S.WITH_DEFICIENCY], [S.HARDCOPY_RECEIVED]:[S.ORIGINALS_VERIFIED],
    [S.ORIGINALS_VERIFIED]:[S.FOR_PO_PROCESSING], [S.FOR_PO_PROCESSING]:[S.FOR_PD_ENDORSEMENT],
    [S.FOR_PD_ENDORSEMENT]:[S.READY_FOR_RO_TRANSMITTAL], [S.READY_FOR_RO_TRANSMITTAL]:[S.TRANSMITTED_TO_REGIONAL_OFFICE],
    [S.TRANSMITTED_TO_REGIONAL_OFFICE]:[S.REGIONAL_OFFICE_PROCESSING,S.RETURNED_BY_REGIONAL_OFFICE,S.NTTC_RECEIVED_FROM_RO],
    [S.REGIONAL_OFFICE_PROCESSING]:[S.RETURNED_BY_REGIONAL_OFFICE,S.NTTC_RECEIVED_FROM_RO],
    [S.RETURNED_BY_REGIONAL_OFFICE]:[S.FOR_COMPLIANCE_WITH_RO_FINDING,S.RETRANSMITTED_TO_REGIONAL_OFFICE],
    [S.FOR_COMPLIANCE_WITH_RO_FINDING]:[S.RETRANSMITTED_TO_REGIONAL_OFFICE],
    [S.RETRANSMITTED_TO_REGIONAL_OFFICE]:[S.REGIONAL_OFFICE_PROCESSING,S.RETURNED_BY_REGIONAL_OFFICE,S.NTTC_RECEIVED_FROM_RO],
    [S.NTTC_RECEIVED_FROM_RO]:[S.CERTIFICATE_RECORDED], [S.CERTIFICATE_RECORDED]:[S.CERTIFICATE_READY_FOR_RELEASE],
    [S.CERTIFICATE_READY_FOR_RELEASE]:[S.RELEASED], [S.RELEASED]:[S.CLOSED], [S.CLOSED]:[]
  });
  function canTransition(from,to){ return (transitions[from]||[]).includes(to); }
  function assertTransition(from,to){ if(!canTransition(from,to)) throw new Error(`Invalid NTTC status transition: ${from} -> ${to}`); return true; }
  function applicantStage(status){
    const C=TAESF.NTTC.Constants.APPLICANT_STAGE;
    if([S.DRAFT,S.READY_FOR_ONLINE_SUBMISSION].includes(status)) return C.DRAFT;
    if([S.SUBMITTED_FOR_INITIAL_REVIEW,S.UNDER_INITIAL_REVIEW,S.COMPLIANCE_SUBMITTED,S.UNDER_RE_REVIEW].includes(status)) return C.REVIEW;
    if([S.WITH_DEFICIENCY,S.FOR_COMPLIANCE_WITH_RO_FINDING,S.RETURNED_BY_REGIONAL_OFFICE].includes(status)) return C.COMPLIANCE;
    if([S.APPROVED_FOR_HARDCOPY_SUBMISSION,S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED,S.APPLICANT_ARRIVED,S.HARDCOPY_UNDER_VERIFICATION].includes(status)) return C.HARDCOPY_READY;
    if([S.HARDCOPY_RECEIVED,S.ORIGINALS_VERIFIED,S.FOR_PO_PROCESSING,S.FOR_PD_ENDORSEMENT,S.READY_FOR_RO_TRANSMITTAL].includes(status)) return C.HARDCOPY_RECEIVED;
    if([S.TRANSMITTED_TO_REGIONAL_OFFICE,S.RETRANSMITTED_TO_REGIONAL_OFFICE].includes(status)) return C.RO;
    if(status===S.REGIONAL_OFFICE_PROCESSING) return C.RO_PROCESSING;
    if([S.NTTC_RECEIVED_FROM_RO,S.CERTIFICATE_RECORDED,S.CERTIFICATE_READY_FOR_RELEASE].includes(status)) return C.READY;
    if([S.RELEASED,S.CLOSED].includes(status)) return C.RELEASED;
    return status;
  }
  return Object.freeze({transitions,canTransition,assertTransition,applicantStage});
})();
