"use strict";
TAESF.NTTC.FocalHardcopyView=(()=>{
  function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));}
  function appointment(record){const a=record.appointment||{};return`${a.date||"Not scheduled"}${a.timeFrom?` • ${a.timeFrom}${a.timeTo?`–${a.timeTo}`:""}`:""}`;}
  function requestPanel(record){const r=record.scheduleRequest;if(!r||r.status!=="PENDING")return"";return `<div class="focal-schedule-request"><div><span class="eyebrow">APPLICANT REQUEST</span><h3>Alternative schedule requested</h3><p><strong>Preferred:</strong> ${esc(r.preferredDate)} ${r.preferredTimeFrom?`• ${esc(r.preferredTimeFrom)}${r.preferredTimeTo?`–${esc(r.preferredTimeTo)}`:""}`:""}</p><p><strong>Reason:</strong> ${esc(r.reason)}</p><small>Requested ${new Date(r.requestedAt).toLocaleString()}</small></div><div><button id="acceptApplicantSchedule" class="primary">Accept Preferred Schedule</button><button id="offerAnotherSchedule" class="secondary">Offer Different Schedule</button></div></div>`;}
  function render(application,applicant,record){const S=TAESF.NTTC.Constants.STATUS,st=application.status,a=record.appointment||{},v=record.verification||{};
    if(st===S.APPROVED_FOR_HARDCOPY_SUBMISSION)return `<section class="hardcopy-stage-card"><div class="stage-card-head"><div><span class="eyebrow">NEXT ACTION</span><h2>Schedule Hard-Copy Submission</h2><p>Assign the date when the applicant will bring the notarized Form A, hard-copy supporting documents, and originals for verification. The applicant can confirm or request another schedule.</p></div><span class="stage-number">01</span></div><form id="appointmentForm" class="hardcopy-form"><label><span>Date</span><input type="date" name="date" required></label><label><span>Time From</span><input type="time" name="timeFrom" required></label><label><span>Time To</span><input type="time" name="timeTo"></label><label class="span-2"><span>Venue</span><input name="venue" value="TESDA Albay Provincial Office" required></label><label class="span-2"><span>Applicant Instructions</span><textarea name="instructions" rows="3">Bring the notarized Form A and the complete hard-copy supporting documents. Bring original documents for verification.</textarea></label><div class="span-2 form-actions"><button class="primary" type="submit">Save Submission Schedule</button></div></form></section>`;
    if([S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED].includes(st))return `<section class="hardcopy-stage-card"><div class="stage-card-head"><div><span class="eyebrow">SCHEDULED SUBMISSION</span><h2>${esc(appointment(record))}</h2><p>${esc(a.venue||"")}</p></div><span class="stage-number">02</span></div><div class="appointment-detail"><p>${esc(a.instructions||"")}</p><div><strong>Applicant confirmation</strong><span>${record.confirmedAt?`Confirmed ${new Date(record.confirmedAt).toLocaleString()}`:"Not yet confirmed in the applicant portal"}</span></div></div>${requestPanel(record)}<button id="confirmArrival" class="primary">Confirm Applicant Arrival</button></section>`;
    if([S.APPLICANT_ARRIVED,S.HARDCOPY_UNDER_VERIFICATION].includes(st))return `<section class="hardcopy-stage-card"><div class="stage-card-head"><div><span class="eyebrow">PHYSICAL SUBMISSION</span><h2>Verify Hard Copy & Originals</h2><p>Confirm the prescribed Form A is notarized and compare the hard-copy documents with the originals presented.</p></div><span class="stage-number">03</span></div><form id="hardcopyVerificationForm" class="verification-checklist"><label><input type="checkbox" name="notarizedFormA" ${v.notarizedFormA?"checked":""}><span><strong>Notarized Form A</strong><small>Prescribed CoCIE Application Form is signed and notarized.</small></span></label><label><input type="checkbox" name="ncHardcopy" ${v.ncHardcopy?"checked":""}><span><strong>National Certificate hard copy</strong><small>Hard copy corresponds with the online submission.</small></span></label><label><input type="checkbox" name="tmcHardcopy" ${v.tmcHardcopy?"checked":""}><span><strong>TMC I hard copy</strong><small>Hard copy corresponds with the online submission.</small></span></label><label><input type="checkbox" name="iwerHardcopy" ${v.iwerHardcopy?"checked":""}><span><strong>IWER supporting documents</strong><small>Complete supporting evidences listed in Form A are physically submitted.</small></span></label><label><input type="checkbox" name="originalsPresented" ${v.originalsPresented?"checked":""}><span><strong>Original documents presented</strong><small>Originals were presented for comparison/verification.</small></span></label><label class="verification-remarks"><span>Verification remarks</span><textarea name="remarks" rows="3">${esc(v.remarks||"")}</textarea></label><div class="verification-actions"><button id="saveHardcopyVerification" type="button" class="secondary">Save Checklist</button><button id="receiveHardcopy" type="button" class="primary">Receive Complete Application</button></div></form></section>`;
    if([S.HARDCOPY_RECEIVED,S.ORIGINALS_VERIFIED,S.FOR_PO_PROCESSING,S.FOR_PD_ENDORSEMENT,S.READY_FOR_RO_TRANSMITTAL].includes(st))return `<section class="hardcopy-stage-card completed"><div class="stage-card-head"><div><span class="eyebrow">PHYSICAL SUBMISSION COMPLETE</span><h2>Hard Copy Received</h2><p>Received ${record.receivedAt?new Date(record.receivedAt).toLocaleString():""} by ${esc(record.receivedBy||"—")}.</p></div><span class="stage-number">✓</span></div><div class="claim-stub-summary"><div><span>Claim Stub No.</span><strong>${esc(record.claimStubNumber||"—")}</strong></div><button id="printClaimStub" class="primary">Print Claim Stub</button></div></section>`;return"";
  }
  return Object.freeze({render});
})();
