"use strict";
NEXUS_SPECTRA.Views.Accounting=(()=>{
 const esc=s=>(s??"").toString().replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 const peso=n=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n||0));

 function queue(rows){
   const body=document.getElementById("accountingQueueBody");
   body.innerHTML=rows.length
     ? rows.map(r=>`<tr>
         <td><button class="link-btn" data-acc-open="${esc(r.transactionNo)}"><strong>${esc(r.transactionNo)}</strong></button><br><small>${esc(r.controlNo||"")}</small></td>
         <td>${esc(r.rqmCode||r.rqmNo)}</td>
         <td>${esc(r.tvi)}<br><small>${esc(r.qualification)}</small></td>
         <td>${peso(r.claimAmount)}</td>
         <td><span class="status-pill">${esc(r.status.replaceAll("_"," "))}</span></td>
       </tr>`).join("")
     : '<tr><td colspan="5" class="empty">No cases are currently in Accounting Review.</td></tr>';
 }

 async function detail(no){
   const host=document.getElementById("accountingReviewDetail");
   if(!no){host.innerHTML='<div class="empty">Select a case from the Accounting Review queue.</div>';return;}
   const tx=NEXUS_SPECTRA.Repository.Transactions.get(no);
   const r=NEXUS_SPECTRA.Services.Accounting.ensure(no);
   if(!tx||!r){host.innerHTML='<div class="empty">Accounting review record not found.</div>';return;}

   const docs=await NEXUS_SPECTRA.Services.Documents.list(no);
   const docHtml=docs.length
     ? docs.map(d=>`<article class="online-doc"><div><strong>${esc(d.docType.replaceAll("_"," "))}</strong><small>${esc(d.fileName)}</small></div><button class="btn" data-online-doc="${esc(d.documentId)}">View</button></article>`).join("")
     : '<div class="empty">No online supporting files attached.</div>';

   const sys=Object.entries(r.systemChecks).map(([k,v])=>`<div class="sys-check ${v.ok?"pass":"fail"}"><span>${v.ok?"✓":"!"}</span><div><strong>${esc(k.replaceAll("_"," "))}</strong><small>${esc(v.detail||"")}</small></div></div>`).join("");

   const ck=r.checklist.map(x=>`<tr>
     <td>${esc(x.label)}</td>
     <td><select data-acc-check="${esc(x.id)}">
       <option value="PENDING" ${x.result==="PENDING"?"selected":""}>Pending</option>
       <option value="PASSED" ${x.result==="PASSED"?"selected":""}>Passed</option>
       <option value="FAILED" ${x.result==="FAILED"?"selected":""}>Failed</option>
     </select></td>
     <td><input data-acc-remarks="${esc(x.id)}" value="${esc(x.remarks||"")}" placeholder="Remarks"></td>
   </tr>`).join("");

   const ready=NEXUS_SPECTRA.Services.Accounting.readiness(no);
   host.innerHTML=`<div class="review-head">
     <div><h2>${esc(no)}</h2><p>${esc(tx.rqmCode||tx.rqmNo)} · ${esc(tx.tvi)} · ${esc(tx.qualification)}</p></div>
     <div><span class="status-pill">${esc(tx.status.replaceAll("_"," "))}</span></div>
   </div>
   <div class="reviewer-line">
     <label>Accounting Reviewer</label>
     <input id="accountingReviewer" value="${esc(r.reviewer||"")}" placeholder="Name of reviewer">
     <button class="btn" data-acc-save-reviewer>Save Reviewer</button>
   </div>
   <h3>1. System Review</h3>
   <div class="system-check-grid">${sys}</div>
   <h3>2. School Allowance / Payroll Preview — Finalized SAM Snapshot</h3>${NEXUS_SPECTRA.Views.AuditDetail.preview(tx)}
   <h3>3. Individual Scholar Attendance Review</h3><p class="subtle">Accounting may inspect each scholar/date and save an accounting-specific finding without changing the school-submitted attendance.</p>${NEXUS_SPECTRA.Views.AuditDetail.attendance(tx,"ACCOUNTING",r.reviewer)}
   <h3>4. Online Files Submitted by TVET Provider</h3>
   <div class="online-doc-grid">${docHtml}</div>
   <h3>5. Accounting Review Checklist</h3>
   <div class="table-wrap"><table><thead><tr><th>Requirement</th><th>Result</th><th>Remarks</th></tr></thead><tbody>${ck}</tbody></table></div>
   <div class="inline-actions"><button class="btn" data-acc-save-checklist>Save Accounting Checklist</button></div>
   <h3>6. Provincial Office Payroll</h3>
   <p class="subtle">Payroll is generated by Accounting from the same finalized SAM snapshot. Schools do not generate this document.</p>
   <div class="review-actions">
     <button class="btn" data-acc-payroll>Generate / Review Appendix 33 Payroll — 3 Copies</button>
     <button class="btn primary" data-acc-forward ${ready.ok?"":"disabled"}>Verify & Forward to Budget / Obligation</button>
   </div>
   <div class="readiness-box ${ready.ok?"ok":"warn"}">${ready.ok
      ?"Accounting review is complete and ready for Budget/Obligation."
      :`<strong>Not ready:</strong><ul>${ready.errors.map(e=>`<li>${esc(e)}</li>`).join("")}</ul>`}</div>`;
 }
 return Object.freeze({queue,detail});
})();