"use strict";
NEXUS_SPECTRA.Views.AuditDetail=(()=>{
 const esc=s=>(s??"").toString().replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 const peso=n=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n||0));
 function preview(tx){const rows=NEXUS_SPECTRA.Services.AuditDetail.scholars(tx);return `<div class="table-wrap"><table><thead><tr><th>Scholar</th><th>Present</th><th>Absent</th><th>Rate</th><th>TSF Initial 50%</th><th>TSF Remaining / Final</th><th>Total TSF</th><th>Status</th></tr></thead><tbody>${rows.map(r=>{const initial=Math.min(Number(r.maxTsf||0)/2,Number(r.earned||0)),remaining=Math.max(0,Number(r.earned||0)-initial);return `<tr><td><strong>${esc(r.name)}</strong><br><small>${esc(r.email||"")}</small></td><td>${r.presentDays}</td><td>${r.absentDays}</td><td>${peso(r.rate)}</td><td><strong>${peso(initial)}</strong></td><td><strong>${peso(remaining)}</strong></td><td><strong>${peso(r.earned)}</strong></td><td>${r.isReady?"Ready":"Review"}</td></tr>`}).join("")}</tbody></table></div>`;}
 function attendance(tx,stage,reviewer){
   const scholars=NEXUS_SPECTRA.Services.AuditDetail.scholars(tx);if(!scholars.length)return '<div class="empty">No scholar attendance in snapshot.</div>';
   const first=scholars[0];
   return `<div class="attendance-audit" data-audit-stage="${esc(stage)}" data-audit-transaction="${esc(tx.transactionNo)}"><div class="audit-toolbar"><label>Scholar</label><select data-audit-scholar>${scholars.map((s,i)=>`<option value="${esc(s.key)}" ${i===0?"selected":""}>${esc(s.name)}</option>`).join("")}</select><button class="btn" data-audit-load>View Daily Time In / Out</button></div><div data-audit-daily>${dailyTable(tx,stage,first.key,reviewer)}</div></div>`;
 }
 function dailyTable(tx,stage,key,reviewer){const days=NEXUS_SPECTRA.Services.AuditDetail.days(tx,key);return `<div class="table-wrap"><table><thead><tr><th>Date</th><th>BSRS In</th><th>BSRS Out</th><th>Final In</th><th>Final Out</th><th>Status / Source</th><th>Reviewer Finding</th><th>Remarks</th><th></th></tr></thead><tbody>${days.map(d=>{const note=NEXUS_SPECTRA.Repository.AuditNotes.find(tx.transactionNo,stage,d.reportId,d.scholarNo);return `<tr><td>${esc(d.date)}<br><small>Report ${esc(d.reportNumber)}</small></td><td>${esc(d.bsrsIn||"—")}</td><td>${esc(d.bsrsOut||"—")}</td><td>${esc(d.finalIn||"—")}</td><td>${esc(d.finalOut||"—")}</td><td>${esc(d.finalStatus.replaceAll("_"," "))}<br><small>${esc(d.source||"")}</small></td><td><select data-audit-finding><option value="NONE" ${!note||note.finding==="NONE"?"selected":""}>No Finding</option><option value="FOR_CLARIFICATION" ${note?.finding==="FOR_CLARIFICATION"?"selected":""}>For Clarification</option><option value="DEFICIENT" ${note?.finding==="DEFICIENT"?"selected":""}>Deficient</option><option value="VERIFIED" ${note?.finding==="VERIFIED"?"selected":""}>Verified</option></select></td><td><input data-audit-remarks value="${esc(note?.remarks||"")}" placeholder="Reviewer note"></td><td><button class="btn" data-audit-save data-report-id="${esc(d.reportId)}" data-report-no="${esc(d.reportNumber)}" data-date="${esc(d.date)}" data-scholar-no="${d.scholarNo}" data-scholar-name="${esc(d.name)}">Save</button></td></tr>`;}).join("")}</tbody></table></div>`;}
 return Object.freeze({preview,attendance,dailyTable});
})();