"use strict";
NEXUS_SAM.Modules.Attendance.BsrsParser = (()=>{
 const val=(re,text)=>{const m=text.match(re);return m?m[1].trim():"";};
 const normalizeTime=v=>{v=(v||"").trim();return (!v||v==="-"||v==="–")?"":v;};
 function splitRow(line){
   const m=line.match(/^\s*(\d{1,3})\s+(.+?)\s+((?:09|08|07|\+63)\d[\d\- ]{7,})\s+([A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,})\s+(.+)$/i);
   if(!m)return null;
   const no=Number(m[1]), beforeContact=m[2].trim(), contact=m[3].trim(), email=m[4].trim(), tail=m[5].trim();
   const timeMatches=[...tail.matchAll(/(?:\b\d{1,2}:\d{2}\s*(?:AM|PM)\b|(?<!\S)-(?!\S))/gi)].map(x=>x[0]);
   let timeIn="",timeOut="",duration="";
   if(timeMatches.length>=1) timeIn=normalizeTime(timeMatches[0]);
   if(timeMatches.length>=2) timeOut=normalizeTime(timeMatches[1]);
   const dur=tail.match(/(\d{1,2}\s*:\s*\d{1,2}|-)\s*$/); if(dur&&dur[1].trim()!=="-")duration=dur[1].trim();
   const addrMarkers=/\b(?:P-?\d+|PUROK|ZONE|BRGY\.?|BARANGAY|BLK|BLOCK|SITIO|ST\.?|STREET|RAWIS|OYAMA|NAGAS|SAN\s|648\b)/i;
   const am=addrMarkers.exec(beforeContact); let name,address;
   if(am){name=beforeContact.slice(0,am.index).trim();address=beforeContact.slice(am.index).trim();}
   else {
     const comma=beforeContact.indexOf(",");
     if(comma>0){const words=beforeContact.slice(comma+1).trim().split(/\s+/);const take=Math.min(3,words.length);name=beforeContact.slice(0,comma+1)+" "+words.slice(0,take).join(" ");address=words.slice(take).join(" ");}
     else {name=beforeContact;address="";}
   }
   return {no,name:name.replace(/\s+/g," ").trim(),address:address.replace(/\s+/g," ").trim(),contact,email,timeIn,timeOut,duration};
 }
 function parse(extracted){
   const text=extracted.text.replace(/\u00a0/g," ");
   if(!/Biometric-Enabled Scholarship Registration System|BSRS/i.test(text)||!/ATTENDANCE SHEET/i.test(text)) throw new Error("The selected PDF does not appear to be a BSRS Trainees'/Learners' Attendance Sheet.");
   const metadata={
     reportNumber:val(/Report Number:\s*([^\n]+)/i,text),
     attendanceDate:val(/\bDate:\s*([A-Z]+\s+\d{1,2},\s*\d{4})/i,text),
     scholarshipProgram:val(/\n([^\n]+(?:Scholarship Program|TWSP|TTSP|PESFA|BKSTP)[^\n]*)\n/i,text),
     tvi:val(/Name of TVI:\s*(.+?)(?=\s+Date:|\n)/i,text),
     qualification:val(/Qualification\/Program:\s*(.+?)(?=\s+Name of Trainer:|\n)/i,text),
     trainer:val(/Name of Trainer:\s*(.+?)(?=\s+NTTC No\.:|\n)/i,text),
     nttcNo:val(/NTTC No\.:\s*([^\n]+)/i,text),
     trainingLocation:val(/Location of Training:\s*([^\n]+)/i,text),
     generatedBy:val(/Generated by:\s*([^\n]+)/i,text),
     generatedAt:val(/Generated by:[^\n]*\nDate:\s*([^\n]+)/i,text)
   };
   const session=text.match(/Session Start\/End:\s*([^\s]+\s*(?:AM|PM))\s*-\s*([^\n]+?(?:AM|PM))/i); if(session){metadata.sessionStart=session[1].trim();metadata.sessionEnd=session[2].trim();}
   const train=text.match(/Date Start\/End:\s*([A-Z]+\s+\d{1,2},\s*\d{4})\s*-\s*([A-Z]+\s+\d{1,2},\s*\d{4})/i); if(train){metadata.trainingStart=train[1];metadata.trainingEnd=train[2];}
   metadata.approvedDailyDuration=val(/Duration \(based on approved CTPR\).*?:\s*([^\n]+)/i,text);
   const candidate=[];
   extracted.pages.forEach(page=>page.lines.forEach(line=>{const r=splitRow(line);if(r)candidate.push(r);}));
   const counts={};candidate.forEach(r=>counts[r.no]=(counts[r.no]||0)+1);
   const duplicateScholarNos=Object.keys(counts).filter(k=>counts[k]>1).map(Number);
   const byNo=new Map(); candidate.forEach(r=>{const old=byNo.get(r.no);if(!old||JSON.stringify(r).length>JSON.stringify(old).length)byNo.set(r.no,r);});
   const scholars=[...byNo.values()].sort((a,b)=>a.no-b.no);
   if(!scholars.length) throw new Error("BSRS report was recognized, but no scholar attendance rows could be extracted. Please check the PDF format.");
   const emails=scholars.map(s=>s.email.toUpperCase()).filter(Boolean);
   const duplicateEmails=[...new Set(emails.filter((e,i)=>emails.indexOf(e)!==i))];
   return {...metadata,scholars,diagnostics:{rawCandidateRows:candidate.length,uniqueScholarRows:scholars.length,duplicateScholarNos,duplicateEmails}};
 }
 return Object.freeze({parse,splitRow});
})();