"use strict";
TAESF.NTTC.CoCIEFormView=(()=>{
  const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
  function date(v){if(!v)return"";const d=new Date(v+(/T/.test(v)?"":"T00:00:00"));return Number.isNaN(d.getTime())?esc(v):String(d.getMonth()+1).padStart(2,"0")+"/"+String(d.getDate()).padStart(2,"0")+"/"+d.getFullYear();}
  function box(on){return `<span class="prescribed-box">${on?"✓":""}</span>`;}
  function checked(actual,value){return String(actual||"").toLowerCase()===String(value||"").toLowerCase();}
  function employment(d){const s=String(d.employmentStatus||"");return {casual:/casual/i.test(s),permanent:/permanent|regular/i.test(s),contractual:/contractual/i.test(s),self:/self-employed/i.test(s),other:!/casual|permanent|regular|contractual|self-employed/i.test(s)&&!!s,text:s};}
  function rows(application,start,count){const src=TAESF.NTTC.CoCIEFormService.evidenceRows(application.applicationId).slice(start,start+count);const html=src.map(r=>{const m=TAESF.NTTC.CoCIEFormService.modalityLetter(r.modality);return `<tr><td>${esc(r.tabCode)}</td><td class="left">${esc(r.evidence)}</td><td>${date(r.fromDate)}</td><td>${date(r.toDate)}</td><td>${m==="A"?"✓":""}</td><td>${m==="B"?"✓":""}</td><td>${m==="C"?"✓":""}</td><td>${m==="D"?"✓":""}</td><td>${esc(r.estimatedHours)}</td></tr>`}).join("");return html+Array.from({length:Math.max(0,count-src.length)},()=>`<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>`).join("");}
  function evidenceHeader(){return `<thead><tr><th rowspan="2">Tab<br>Code</th><th rowspan="2">Evidences</th><th colspan="2">Inclusive Dates</th><th colspan="4">Modalities</th><th rowspan="2">Estimated<br>Number of<br>Equivalent<br>Hours</th></tr><tr><th>From</th><th>To</th><th>A</th><th>B</th><th>C</th><th>D</th></tr></thead>`;}
  function render(p,application){p=p||{};const d=application.applicationDetails||{},emp=employment(d),full=p.fullName||[p.firstName,p.middleName,p.lastName,p.extensionName].filter(Boolean).join(" ");
    return `<section class="prescribed-form-page page-one"><div class="prescribed-form-code">Form A</div><div class="prescribed-header"><img src="../../assets/Logo.png" alt="TESDA"><div><div class="agency">Technical Education and Skills Development Authority</div><div class="region">Region V</div><h1>APPLICATION FORM</h1><h2>CERTIFICATE OF COMPLIANCE TO INDUSTRY EXPERIENCE (CoCIE)</h2></div><div class="photo-box"></div></div>
    <table class="prescribed-table identity"><tr><th>SECTOR</th><td colspan="5">${esc(application.sector||"")}</td><th colspan="3" class="qualification-label">TITLE OF QUALIFICATION<br><small>(Qualification applying for Certificate of<br>Compliance to Industry Experience)</small></th><td colspan="7">${esc(application.qualificationTitle||"")}</td></tr><tr><th colspan="4">Last Name</th><td colspan="12">${esc(p.lastName)}</td></tr><tr><th colspan="4">First Name</th><td colspan="12">${esc(p.firstName)}</td></tr><tr><th colspan="4">Middle Name</th><td colspan="9">${esc(p.middleName)}</td><td colspan="3"><small>Name Extension<br>(e.g. Jr., Sr.)</small><br>${esc(p.extensionName)}</td></tr><tr><th colspan="4">Complete Address</th><td colspan="12">${esc(p.address)}</td></tr><tr><th colspan="3">Date of Birth <small>(mm/dd/yyyy)</small></th><td colspan="3">${date(p.dateOfBirth)}</td><th colspan="2">Place of Birth</th><td colspan="3">${esc(p.placeOfBirth)}</td><th>Height: (m)</th><td colspan="2">${esc(p.heightM)}</td><th>Weight: (k)</th><td>${esc(p.weightKg)}</td></tr><tr><th colspan="4">School/Institution</th><td colspan="8">${esc(d.tviName)}</td><th>Tel. No.</th><td colspan="3">${esc(p.telephone)}</td></tr><tr><th colspan="4">Address</th><td colspan="12">${esc(p.institutionAddress)}</td></tr></table>
    <table class="prescribed-table options"><tr><th>Sex</th><th>Civil Status</th><th>Contact Numbers</th><th>Highest Educational<br>Attainment</th><th>Employment Status</th></tr><tr><td>${box(checked(p.sex,"Male"))} Male<br><br>${box(checked(p.sex,"Female"))} Female</td><td>${box(checked(p.civilStatus,"Single"))} Single<br><br>${box(checked(p.civilStatus,"Married"))} Married<br><br>${box(checked(p.civilStatus,"Widow/er"))} Widow/er<br><br>${box(checked(p.civilStatus,"Separated"))} Separated</td><td>Tel: ${esc(p.telephone)}<br><br>Mobile Phone: ${esc(p.mobile)}<br><br>e-mail: ${esc(p.email)}<br><br>Fax:</td><td>${box(checked(p.highestEducation,"TVET Graduate"))} TVET Graduate<br><br>${box(checked(p.highestEducation,"College Level"))} College Level<br><br>${box(checked(p.highestEducation,"College Graduate"))} College Graduate<br><br>${box(checked(p.highestEducation,"Post Graduate"))} Post Graduate</td><td>${box(emp.casual)} Casual &nbsp;&nbsp; ${box(emp.permanent)} Permanent<br><br>${box(emp.contractual)} Contractual &nbsp;&nbsp; ${box(emp.self)} Self-employed<br><br>${box(emp.other)} Others, pls. specify ${emp.other?esc(emp.text):"____________"}</td></tr></table>
    <div class="prescribed-instructions"><strong>Instructions:</strong><ol><li>Assign Tab Code to each set of evidence (<em>one set of evidence per project, job, course</em>) that are submitting in this assessment.</li><li>Write the details of the evidences on the table below (<em>Tab Code in the this table should be consistent with the Tab Code in attached document/evidence</em>)</li><li>Indicate the estimated equivalent hours of your work experience. Refer to the marking scheme per modality described below:<div class="instruction-modalities">A. &nbsp; Pre-Service industry Work Experience (1hr:1hr)<br>B. &nbsp; Industry Immersion (1hr:1hr)<br>C. &nbsp; DTP/DTS/OJT (1hr:0.5hr)<br>D. &nbsp; Technical Consulting for MSMEs Productivity Enhancement (1hr:1hr/Enterprise)<br><em>Note: Conversion of day to hour; 1 day = 8 hours, 22 days per month</em></div></li></ol></div>
    <table class="prescribed-table evidence-table">${evidenceHeader()}<tbody>${rows(application,0,8)}</tbody></table></section>
    <section class="prescribed-form-page page-two"><div class="prescribed-form-code">Form A</div><table class="prescribed-table evidence-table continuation">${evidenceHeader()}<tbody>${rows(application,8,10)}</tbody></table><div class="notarization-warning">This form should be notarized in order that the supporting documents can be considered legal and valid. Only supporting documents herein will be correspondingly credited.</div><div class="declaration"><strong class="section-letter">A</strong> I declare under oath that this Application Form and the attached supporting documents are true, correct, and exact copy of the authentic document, pursuant to the provisions of pertinent laws, rules and regulations of the Republic of the Philippines.</div><table class="prescribed-table declaration-table"><tr><th></th><th>Name</th><th>Government Issued ID Type<br>and No.</th><th>Signature</th></tr><tr><th>Applicant</th><td>${esc(full)}</td><td>${esc(p.governmentIdTypeNo||"")}</td><td></td></tr></table><div class="notarial"><strong class="section-letter">B</strong> <strong>SUBSCRIBED AND SWORN TO</strong> before me, this ______ day of _______________ , 20 ____ at _______________________________.<div class="notarial-register">Doc No: ____________<br>Page No: ___________<br>Book No: ___________<br>Series: _____________</div></div><table class="prescribed-table certification-table"><tr><td><em>I certify that the submitted supporting documents are exact copies of the original.</em><div class="signature-space"></div>Signature over Printed Name<br><strong>Screening/Records Officer</strong><br>Date:<br><br><br>Endorsed by:<div class="signature-space endorser-name">${esc(d.endorserName||"")}</div>Signature over Printed Name<br><strong>TVI Administrator/President</strong><br>Date:</td><td><em>This is to certify that I have received the exact number of attached supporting documents as listed above.</em><br><br>Received by:<div class="received-space"></div><strong>Name and Signature of TESDA Provincial Office Representative</strong><br>Date:</td></tr></table></section>`;
  }
  return Object.freeze({render});
})();
