"use strict";
TAESF.NTTC.ApplicantComplianceView=(()=>{
 function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));}
 function render(applicant,application,deficiencies){
  const items=deficiencies.map((d,i)=>{const complied=d.status==="COMPLIED_PENDING_REVIEW";const file=d.complianceDocumentId?TAESF.NTTC.DocumentRepository.findById(d.complianceDocumentId):null;return `<article class="compliance-card ${complied?"complete":""}"><div class="compliance-index">${complied?"✓":i+1}</div><div class="compliance-body"><div class="compliance-head"><div><span class="eyebrow">FINDING ${i+1}</span><h3>${esc(d.finding)}</h3></div><span class="status-pill ${complied?"status-ok":"status-action"}">${complied?"COMPLIANCE UPLOADED":"ACTION REQUIRED"}</span></div><div class="required-action"><strong>What you need to do</strong><p>${esc(d.requiredAction)}</p></div>${file?`<div class="compliance-file"><div><strong>${esc(file.fileName)}</strong><span>Uploaded ${new Date(file.uploadedAt).toLocaleString()} • Version ${esc(file.versionNo)}</span></div><button class="secondary compliance-preview" data-id="${esc(file.documentId)}">View</button></div>`:`<label class="compliance-drop"><input class="compliance-input" data-deficiency="${esc(d.deficiencyId)}" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"><span><strong>Choose corrected or additional document</strong><small>PDF, JPG or PNG • maximum 10 MB</small></span></label><button class="primary compliance-upload" data-deficiency="${esc(d.deficiencyId)}">Upload Compliance</button>`}</div></article>`;}).join("");
  const ready=deficiencies.length&&deficiencies.every(x=>x.status==="COMPLIED_PENDING_REVIEW");
  return `<main class="application-shell"><header class="application-topbar"><div class="app-brand"><img src="../../assets/Logo.png" alt="TESDA Logo"><div><span>NEXUS • NTTC APPLICATION MONITORING</span><strong>TESDA Albay Provincial Office</strong></div></div><div class="applicant-menu"><div class="applicant-meta"><strong>${esc(applicant.fullName||"")}</strong><span>${esc(applicant.learnerId||"")}</span></div><button id="myApplications" class="secondary icon-button">My Applications</button><button id="logoutApplicant" class="secondary icon-button">Exit</button></div></header><section class="tracking-shell wide-tracking"><div class="tracking-hero warning-hero"><span class="eyebrow light">ACTION REQUIRED</span><h1>Complete Your Documentary Compliance</h1><p>Upload the corrected or additional document requested for each finding. Your original upload remains preserved in the application history.</p><div class="control-card"><span>Application Control Number</span><strong>${esc(application.controlNumber)}</strong></div></div><div id="complianceMessage" class="message" hidden></div><div class="help-card"><strong>How this works</strong><p>Upload one compliance document for every finding below. When all findings have a compliance upload, select <b>Submit Compliance for Re-Review</b>. The CAC focal will review the new files; uploading a file does not automatically close a finding.</p></div><section class="compliance-stack">${items||"<div class='empty-state'>No open findings were found.</div>"}</section><div class="compliance-submit-bar"><div><strong>${ready?"Ready to resubmit":"Complete all findings first"}</strong><span>${ready?"All open findings have a compliance upload.":"Each finding must have a corrected or additional document."}</span></div><button id="submitCompliance" class="primary modern-primary" ${ready?"":"disabled"}>Submit Compliance for Re-Review <span>→</span></button></div><div class="policy-note"><strong>Important:</strong> Do not create a new NTTC application. Continue using this control number until the application is completed.</div></section></main>`;
 }
 return Object.freeze({render});
})();
