"use strict";
NEXUS_SAM.Modules.TIP=NEXUS_SAM.Modules.TIP||{};
NEXUS_SAM.Modules.TIP.Service=(()=>{
 const SEQ="NEXUS:SPECTRA:tipSequence";const pad=n=>String(n).padStart(6,"0");
 function nextNo(){const y=new Date().getFullYear();let d={year:y,seq:0};try{d=JSON.parse(localStorage.getItem(SEQ)||JSON.stringify(d));}catch(_){}if(Number(d.year)!==y)d={year:y,seq:0};d.seq++;localStorage.setItem(SEQ,JSON.stringify(d));return `TIP-${y}-${pad(d.seq)}`;}
 function activeBatch(){const id=NEXUS_SAM.Modules.Workflow.Controller.activeBatch();return id?NEXUS_SAM.Modules.Batch.Service.get(id):null;}
 function request(input){const b=activeBatch();if(!b)return {ok:false,errors:["Open the scholarship batch before requesting TIP."]};const errors=[];if(!input.requestedDate)errors.push("Preferred TIP date is required.");if(!input.requestedTime)errors.push("Preferred TIP time is required.");if(!input.requestedBy)errors.push("Requested-by name is required.");if(!input.tviEmail)errors.push("TVI official email is required.");if(errors.length)return {ok:false,errors};const now=new Date().toISOString(),row={tipRequestNo:nextNo(),batchId:b.batchId,rqmNo:b.rqmNo||"",rqmCode:b.rqmCode||"",tvi:b.tvi||"",qualification:b.qualificationTitle||"",trainingStartDate:b.trainingStartDate||"",requestedDate:input.requestedDate,requestedTime:input.requestedTime,requestedBy:input.requestedBy,tviEmail:input.tviEmail,remarks:input.remarks||"",status:"REQUESTED",requestedAt:now,scheduledDate:"",scheduledTime:"",conductedAt:"",conductedBy:"",overrideReason:"",schoolConfirmed:false,history:[{at:now,type:"TIP_REQUESTED",by:input.requestedBy,remarks:`Preferred ${input.requestedDate} ${input.requestedTime}`} ]};NEXUS_TIP_SHARED.saveRequest(row);NEXUS_TIP_SHARED.addNotification({audience:"SCHOLARSHIP",type:"TIP_REQUEST",title:"New TIP request",message:`${row.tvi} requested TIP for ${row.qualification} on ${row.requestedDate} ${row.requestedTime}.`,ref:row.tipRequestNo});const cfg=NEXUS_TIP_SHARED.config();if(cfg.officeEmail)NEXUS_TIP_SHARED.queueEmail({to:cfg.officeEmail,subject:`TIP Request ${row.tipRequestNo} – ${row.tvi}`,body:`${row.tvi} requested a Training Induction Program for ${row.qualification}. Preferred schedule: ${row.requestedDate} ${row.requestedTime}. RQM: ${row.rqmCode||row.rqmNo}.`,ref:row.tipRequestNo});return {ok:true,row};}
 function byBatch(){const b=activeBatch();return b?NEXUS_TIP_SHARED.requests().filter(x=>x.batchId===b.batchId).sort((a,b)=>(b.requestedAt||"").localeCompare(a.requestedAt||"")):[];}
 function confirm(no){const r=NEXUS_TIP_SHARED.requests().find(x=>x.tipRequestNo===no);if(!r)return {ok:false};r.schoolConfirmed=true;r.status=r.status==="SCHEDULED"?"CONFIRMED":"CONFIRMED";r.confirmedAt=new Date().toISOString();r.history.push({at:r.confirmedAt,type:"SCHOOL_CONFIRMED",by:"TVET_PROVIDER",remarks:`Confirmed ${r.scheduledDate} ${r.scheduledTime}`});NEXUS_TIP_SHARED.saveRequest(r);NEXUS_TIP_SHARED.addNotification({audience:"SCHOLARSHIP",type:"TIP_CONFIRMATION",title:"TIP schedule confirmed",message:`${r.tvi} confirmed TIP schedule ${r.scheduledDate} ${r.scheduledTime}.`,ref:r.tipRequestNo});return {ok:true,row:r};}
 function notifications(){const b=activeBatch();if(!b)return [];const refs=new Set(NEXUS_TIP_SHARED.requests().filter(x=>x.batchId===b.batchId).map(x=>x.tipRequestNo));return NEXUS_TIP_SHARED.notifications().filter(n=>n.audience==="TVI"&&(n.batchId===b.batchId||refs.has(n.ref))).sort((a,b)=>(b.createdAt||"").localeCompare(a.createdAt||""));}
 return Object.freeze({request,byBatch,confirm,notifications});
})();