"use strict";
NEXUS_SAM.Modules.MIS=NEXUS_SAM.Modules.MIS||{};
NEXUS_SAM.Modules.MIS.Service=(()=>{
 const KEY="NEXUS:SAM:misSubmissions",norm=s=>String(s||"").trim().toUpperCase().replace(/\s+/g," "),text=v=>String(v??"").trim();
 const all=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]");}catch(_){return []}},saveAll=r=>localStorage.setItem(KEY,JSON.stringify(r));
 function identity(r){const uli=text(r.U),t2=text(r.BA),name=[text(r.Q),text(r.R),text(r.S),text(r.T)].filter(Boolean).join(", "),dob=text(r.AD);return uli?`ULI:${norm(uli)}`:t2?`T2MIS:${norm(t2)}`:`NAME:${norm(name)}|${dob}`;}
 function parse(ws,rqm){const rows=XLSX.utils.sheet_to_json(ws,{header:"A",range:0,defval:"",raw:false}),out=[];for(let i=5;i<rows.length;i++){const r=rows[i],code=text(r.A);if(!code||norm(code)!==norm(rqm))continue;if(!text(r.Q)&&!text(r.R)&&!text(r.U)&&!text(r.BA))continue;out.push({row:i+1,identity:identity(r),rqmCode:code,provider:text(r.F),qualification:text(r.L),lastName:text(r.Q),firstName:text(r.R),middleName:text(r.S),extension:text(r.T),uli:text(r.U),t2misUli:text(r.BA),sex:text(r.AC),birthDate:text(r.AD),trainingStatus:text(r.AJ),trainingStart:text(r.AM),trainingEnd:text(r.AN),trainingResult:text(r.AO),assessmentDate:text(r.AP),assessmentResult:text(r.AQ),assessmentSchedule:text(r.BE)});}return out;}
 function compare(rqm,rows){let official=[];try{official=JSON.parse(localStorage.getItem("NEXUS:SPECTRA:scholarEnrollments")||"[]").filter(x=>norm(x.rqmCode)===norm(rqm));}catch(_){}
   const officialScholars=(()=>{try{return JSON.parse(localStorage.getItem("NEXUS:SPECTRA:scholarMaster")||"[]");}catch(_){return []}})(),master=new Map(officialScholars.map(s=>[s.scholarId,s]));
   const off=official.map(e=>{const s=master.get(e.scholarId)||{};const id=s.uli?`ULI:${norm(s.uli)}`:s.t2misUli?`T2MIS:${norm(s.t2misUli)}`:`NAME:${norm(s.fullName)}|${s.birthDate||""}`;return {id,e,s};}),offMap=new Map(off.map(x=>[x.id,x])),uploaded=new Map(rows.map(x=>[x.identity,x])),mismatches=[];
   for(const r of rows){const o=offMap.get(r.identity);if(!o){mismatches.push({type:"NOT_IN_OFFICIAL",scholar:`${r.lastName}, ${r.firstName}`,detail:"Uploaded MIS scholar is not found in the current Provincial MIS/SPMOR registry."});continue;}for(const [u,k] of [["trainingStatus","trainingStatus"],["trainingStart","trainingStart"],["trainingEnd","trainingEnd"],["assessmentResult","assessmentResult"]])if(norm(r[u])&&norm(o.e[k])&&norm(r[u])!==norm(o.e[k]))mismatches.push({type:"FIELD_DIFFERENCE",scholar:`${r.lastName}, ${r.firstName}`,field:u,uploaded:r[u],official:o.e[k]});}
   for(const o of off)if(!uploaded.has(o.id))mismatches.push({type:"MISSING_FROM_UPLOAD",scholar:o.s.fullName||o.scholarId,detail:"Official Provincial registry scholar is missing from the provider MIS upload."});
   return {officialCount:official.length,uploadedCount:rows.length,matched:rows.filter(r=>offMap.has(r.identity)).length,mismatches};
 }
 async function submit({file,rqmCode,batchId}){if(!file)return {ok:false,errors:["Select the MIS 03-02 workbook."]};if(!rqmCode)return {ok:false,errors:["Select an approved RQM first."]};if(!window.XLSX)return {ok:false,errors:["Spreadsheet parser is not available."]};const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=wb.SheetNames.find(x=>x.toUpperCase()==="MIS 03-02")||wb.SheetNames[0],rows=parse(wb.Sheets[sheet],rqmCode);if(!rows.length)return {ok:false,errors:[`No MIS 03-02 scholar rows were found for ${rqmCode}.`]};const comparison=compare(rqmCode,rows),record={submissionId:`MIS-${Date.now()}`,rqmCode,batchId:batchId||"",provider:NEXUS_SAM.Modules.RQM.provider().tviName||rows[0].provider,fileName:file.name,sheetName:sheet,submittedAt:new Date().toISOString(),status:comparison.mismatches.length?"FOR_REVIEW":"MATCHED_OFFICIAL",rows,comparison};const allRows=all();allRows.push(record);saveAll(allRows);
   try{await NEXUS_SHARED_DOCS.put({documentId:`MISDOC-${Date.now()}`,transactionNo:"",batchId:batchId||"",docType:"MIS_03_02",fileName:file.name,mimeType:file.type||"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileSize:file.size,remarks:`MIS 03-02 for ${rqmCode}`,uploadedAt:new Date().toISOString(),uploadedBy:record.provider},file);}catch(_){}
   return {ok:true,row:record};
 }
 function latestForRqm(rqm){return all().filter(x=>norm(x.rqmCode)===norm(rqm)).sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt)))[0]||null;}
 return Object.freeze({KEY,all,parse,compare,submit,latestForRqm});
})();