"use strict";
TAESF.NTTC.HardcopyService=(()=>{
  const S=TAESF.NTTC.Constants.STATUS;
  function get(applicationId){return TAESF.NTTC.HardcopyRepository.byApplication(applicationId)||{applicationId,appointment:{date:"",timeFrom:"",timeTo:"",venue:"TESDA Albay Provincial Office",instructions:"Bring the notarized Form A and the complete hard-copy supporting documents. Bring original documents for verification."},scheduleRequest:null,confirmedAt:"",arrivedAt:"",verification:{notarizedFormA:false,ncHardcopy:false,tmcHardcopy:false,iwerHardcopy:false,originalsPresented:false,remarks:""},receivedAt:"",receivedBy:"",claimStubNumber:""};}
  function saveAppointment(applicationId,data){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(![S.APPROVED_FOR_HARDCOPY_SUBMISSION,S.SUBMISSION_SCHEDULED].includes(app.status))throw new Error("This application is not available for scheduling.");if(!data.date||!data.timeFrom||!data.venue)throw new Error("Submission date, start time, and venue are required.");const record=get(applicationId);record.appointment={date:data.date,timeFrom:data.timeFrom,timeTo:data.timeTo||"",venue:String(data.venue||"").trim(),instructions:String(data.instructions||"").trim()};record.scheduledAt=new Date().toISOString();record.confirmedAt="";if(record.scheduleRequest?.status==="PENDING")record.scheduleRequest.status="SUPERSEDED_BY_FOCAL";TAESF.NTTC.HardcopyRepository.save(record);if(app.status===S.APPROVED_FOR_HARDCOPY_SUBMISSION)TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.SUBMISSION_SCHEDULED);return get(applicationId);}
  function confirmAppointment(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status!==S.SUBMISSION_SCHEDULED)throw new Error("This appointment is not awaiting applicant confirmation.");const record=get(applicationId);if(record.scheduleRequest?.status==="PENDING")throw new Error("Your request for another schedule is still awaiting CAC focal action.");record.confirmedAt=new Date().toISOString();TAESF.NTTC.HardcopyRepository.save(record);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.APPOINTMENT_CONFIRMED);return get(applicationId);}
  function requestAlternateSchedule(applicationId,data){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status!==S.SUBMISSION_SCHEDULED)throw new Error("Another schedule can only be requested while the assigned schedule is awaiting confirmation.");if(!data.preferredDate)throw new Error("Enter your preferred date.");if(!String(data.reason||"").trim())throw new Error("Please state why you cannot accept the assigned schedule.");const record=get(applicationId);record.scheduleRequest={requestId:(crypto.randomUUID?crypto.randomUUID():"SCHREQ-"+Date.now()),preferredDate:data.preferredDate,preferredTimeFrom:data.preferredTimeFrom||"",preferredTimeTo:data.preferredTimeTo||"",reason:String(data.reason).trim(),requestedAt:new Date().toISOString(),status:"PENDING",focalRemarks:""};TAESF.NTTC.HardcopyRepository.save(record);return record;}
  function acceptAlternateRequest(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId),record=get(applicationId),req=record.scheduleRequest;if(app.status!==S.SUBMISSION_SCHEDULED||!req||req.status!=="PENDING")throw new Error("No pending applicant schedule request was found.");record.appointment.date=req.preferredDate;record.appointment.timeFrom=req.preferredTimeFrom||record.appointment.timeFrom;record.appointment.timeTo=req.preferredTimeTo||record.appointment.timeTo;record.scheduleRequest.status="ACCEPTED";record.scheduleRequest.decidedAt=new Date().toISOString();record.confirmedAt=new Date().toISOString();TAESF.NTTC.HardcopyRepository.save(record);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.APPOINTMENT_CONFIRMED);return get(applicationId);}
  function offerAlternateSchedule(applicationId,data){const app=TAESF.NTTC.ApplicationService.get(applicationId),record=get(applicationId),req=record.scheduleRequest;if(app.status!==S.SUBMISSION_SCHEDULED||!req||req.status!=="PENDING")throw new Error("No pending applicant schedule request was found.");if(!data.date||!data.timeFrom)throw new Error("Enter the new date and start time.");record.appointment={...record.appointment,date:data.date,timeFrom:data.timeFrom,timeTo:data.timeTo||""};record.scheduleRequest.status="DECLINED_NEW_SCHEDULE_OFFERED";record.scheduleRequest.focalRemarks=String(data.remarks||"").trim();record.scheduleRequest.decidedAt=new Date().toISOString();record.confirmedAt="";TAESF.NTTC.HardcopyRepository.save(record);return get(applicationId);}
  function confirmArrival(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(![S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED].includes(app.status))throw new Error("Applicant arrival can only be recorded for a scheduled application.");const record=get(applicationId);record.arrivedAt=new Date().toISOString();TAESF.NTTC.HardcopyRepository.save(record);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.APPLICANT_ARRIVED);return get(applicationId);}
  function startVerification(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status===S.APPLICANT_ARRIVED)TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.HARDCOPY_UNDER_VERIFICATION);else if(app.status!==S.HARDCOPY_UNDER_VERIFICATION)throw new Error("Hard-copy verification can only start after applicant arrival.");return get(applicationId);}
  function saveVerification(applicationId,data){startVerification(applicationId);const record=get(applicationId);record.verification={notarizedFormA:!!data.notarizedFormA,ncHardcopy:!!data.ncHardcopy,tmcHardcopy:!!data.tmcHardcopy,iwerHardcopy:!!data.iwerHardcopy,originalsPresented:!!data.originalsPresented,remarks:String(data.remarks||"").trim()};TAESF.NTTC.HardcopyRepository.save(record);return record;}
  function checklistComplete(v){return!!(v&&v.notarizedFormA&&v.ncHardcopy&&v.tmcHardcopy&&v.iwerHardcopy&&v.originalsPresented);}function claimNumber(app){const year=(app.controlNumber.match(/-(\d{4})-/)||[])[1]||new Date().getFullYear(),serial=(app.controlNumber.match(/-(\d{6})$/)||[])[1]||String(Date.now()).slice(-6);return`${TAESF.NTTC.Constants.CLAIM_PREFIX}-${year}-${serial}`;}
  function receive(applicationId,receivedBy){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status!==S.HARDCOPY_UNDER_VERIFICATION)throw new Error("Start and complete hard-copy verification first.");const record=get(applicationId);if(!checklistComplete(record.verification))throw new Error("Complete all required hard-copy and original-document checks before receiving the application.");record.receivedAt=new Date().toISOString();record.receivedBy=String(receivedBy||"").trim();if(!record.receivedBy)throw new Error("Receiving personnel name is required.");record.claimStubNumber=record.claimStubNumber||claimNumber(app);TAESF.NTTC.HardcopyRepository.save(record);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.HARDCOPY_RECEIVED);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.ORIGINALS_VERIFIED);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.FOR_PO_PROCESSING);return get(applicationId);}
  function claimStubUrl(applicationId){return`claim-stub.html?applicationId=${encodeURIComponent(applicationId)}`;}
  return Object.freeze({get,saveAppointment,confirmAppointment,requestAlternateSchedule,acceptAlternateRequest,offerAlternateSchedule,confirmArrival,startVerification,saveVerification,checklistComplete,receive,claimStubUrl});
})();
