"use strict";
TAESF.NTTC.CertificateService=(()=>{
  const S=TAESF.NTTC.Constants.STATUS;
  const RO_STATUSES=[S.TRANSMITTED_TO_REGIONAL_OFFICE,S.REGIONAL_OFFICE_PROCESSING,S.RETRANSMITTED_TO_REGIONAL_OFFICE];
  function get(applicationId){return TAESF.NTTC.CertificateRepository.byApplication(applicationId)||{applicationId,certificateNumber:"",issuedOn:"",validUntil:"",receivedOn:"",receivedBy:"",remarks:"",scanFileName:"",scanMimeType:"",release:null};}
  function validateCertificate(data){const errors=[];if(!String(data.certificateNumber||"").trim())errors.push("NTTC certificate number is required.");if(!data.issuedOn)errors.push("Date issued is required.");if(!data.validUntil)errors.push("Validity date is required.");if(!data.receivedOn)errors.push("Date received by the Provincial Office is required.");if(!String(data.receivedBy||"").trim())errors.push("Receiving/recording personnel is required.");return errors;}
  async function recordCertificate(applicationId,data,file){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(!RO_STATUSES.includes(app.status))throw new Error("The application must be at the Regional Office stage before an NTTC certificate can be recorded.");const errors=validateCertificate(data);if(errors.length)throw new Error(errors.join(" "));if(!file)throw new Error("Upload the scanned NTTC certificate for the internal record.");if(!TAESF.NTTC.Constants.ACCEPTED_UPLOAD_MIME.includes(file.type))throw new Error("Certificate scan must be PDF, JPG/JPEG, or PNG.");if(file.size>TAESF.NTTC.Constants.MAX_UPLOAD_BYTES)throw new Error("Certificate scan exceeds the 10 MB file limit.");
    TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.NTTC_RECEIVED_FROM_RO);
    const record=get(applicationId);record.certificateNumber=String(data.certificateNumber).trim();record.issuedOn=data.issuedOn;record.validUntil=data.validUntil;record.receivedOn=data.receivedOn;record.receivedBy=String(data.receivedBy).trim();record.remarks=String(data.remarks||"").trim();record.recordedAt=new Date().toISOString();record.scanFileName=file.name||"NTTC Certificate";record.scanMimeType=file.type||"application/pdf";TAESF.NTTC.CertificateRepository.save(record);await TAESF.NTTC.CertificateRepository.saveScan(applicationId,file);
    TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.CERTIFICATE_RECORDED);
    TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.CERTIFICATE_READY_FOR_RELEASE);
    return get(applicationId);
  }
  async function openInternalScan(applicationId){const stored=await TAESF.NTTC.CertificateRepository.getScan(applicationId);if(!stored)return null;return stored.blob;}
  function release(applicationId,data){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status!==S.CERTIFICATE_READY_FOR_RELEASE)throw new Error("The certificate is not ready for release.");if(!String(data.claimedBy||"").trim())throw new Error("Name of claimant is required.");if(!String(data.idPresented||"").trim())throw new Error("ID presented/reference is required.");const r=get(applicationId);r.release={releasedAt:new Date().toISOString(),releasedBy:String(data.releasedBy||"").trim(),claimedBy:String(data.claimedBy).trim(),idPresented:String(data.idPresented).trim(),claimStubPresented:!!data.claimStubPresented,remarks:String(data.remarks||"").trim()};if(!r.release.releasedBy)throw new Error("Releasing personnel is required.");TAESF.NTTC.CertificateRepository.save(r);TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.RELEASED);return r;}
  async function close(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status!==S.RELEASED)throw new Error("Only a released application can be closed.");const scan=await TAESF.NTTC.CertificateRepository.getScan(applicationId);if(!scan||!scan.blob)throw new Error("The scanned NTTC certificate is required before this application can be closed. Upload/restore the certificate scan first.");TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.CLOSED);return get(applicationId);}
  return Object.freeze({get,recordCertificate,openInternalScan,release,close});
})();
