"use strict";
TAESF.NTTC.FocalDashboardView=(()=>{
 function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));}
 function badge(status){const group=TAESF.NTTC.FocalReviewService.statusGroup(status);return `<span class="focal-status focal-status-${group}">${esc(status.replaceAll("_"," "))}</span>`;}
 function render(applications,metrics){
  const applicantMap=Object.fromEntries((TAESF.NTTC.ApplicantRepository.all?.()||[]).map(a=>[a.applicantId,a]));
  const rows=applications.map(a=>{const p=applicantMap[a.applicantId]||{};const active=["review"].includes(TAESF.NTTC.FocalReviewService.statusGroup(a.status));const hc=TAESF.NTTC.HardcopyRepository?.byApplication?.(a.applicationId),schedulePending=hc?.scheduleRequest?.status==="PENDING";return `<tr data-status="${esc(TAESF.NTTC.FocalReviewService.statusGroup(a.status))}" data-search="${esc([a.controlNumber,p.fullName,a.qualificationTitle,a.status].join(" ").toLowerCase())}"><td><strong class="control-link">${esc(a.controlNumber||"Draft / Pending")}</strong><small>${esc(p.fullName||"Applicant")}</small></td><td><strong>${esc(a.qualificationTitle||"—")}</strong><small>${esc(a.applicationDetails?.tviName||"No institution encoded")}</small></td><td>${badge(a.status)}${schedulePending?`<small class="schedule-change-badge">Schedule change requested</small>`:""}</td><td><span class="date-main">${a.submittedAt?new Date(a.submittedAt).toLocaleDateString():"—"}</span><small>${a.updatedAt?"Updated "+new Date(a.updatedAt).toLocaleString():""}</small></td><td><button class="${active?"primary":"secondary"} focal-open" data-id="${esc(a.applicationId)}">${active?"Review":"View"}</button></td></tr>`}).join("");
  return `<main class="application-shell focal-shell"><header class="application-topbar"><div class="app-brand"><img src="../../assets/Logo.png" alt="TESDA Logo"><div><span>NEXUS • NTTC</span><strong>CAC Focal Workspace</strong></div></div><div class="focal-header-actions"><button id="openQrScanner" class="primary icon-button">Scan Claim Stub QR</button><a class="secondary icon-button" href="index.html">Applicant Portal</a></div></header><section class="focal-hero"><div><span class="eyebrow light">APPLICATION MONITORING</span><h1>NTTC Application Control Center</h1><p>Monitor every online NTTC application, review documentary submissions, track deficiencies, and follow applications through Provincial and Regional Office stages.</p></div><div class="focal-hero-watermark"><img src="../../assets/Logo.png" alt=""></div></section><section class="metric-grid"><article><span>Total Applications</span><strong>${metrics.total}</strong></article><article class="metric-blue"><span>Needs Review</span><strong>${metrics.needsReview}</strong></article><article class="metric-amber"><span>With Deficiency</span><strong>${metrics.withDeficiency}</strong></article><article class="metric-green"><span>Approved for Hard Copy</span><strong>${metrics.approvedHardcopy}</strong></article><article><span>At Regional Office</span><strong>${metrics.regional}</strong></article><article><span>Ready / Certificate Received</span><strong>${metrics.readyRelease}</strong></article></section><section class="workspace-card focal-workspace"><div class="focal-toolbar"><div><span class="eyebrow">CAC FOCAL</span><h2>Application Monitoring</h2><p>Search by control number, applicant, qualification, or filter by processing stage.</p></div><div class="toolbar-controls"><input id="focalSearch" type="search" placeholder="Search applications…"><select id="focalStatusFilter"><option value="all">All statuses</option><option value="review">Needs review</option><option value="deficiency">With deficiency</option><option value="hardcopy">Approved / hard-copy stage</option><option value="provincial">Provincial processing</option><option value="regional">Regional Office</option><option value="release">Certificate / release</option><option value="closed">Released / closed</option><option value="draft">Draft</option></select></div></div><div class="table-wrap"><table class="nexus-table focal-table"><thead><tr><th>Control No. / Applicant</th><th>Qualification / Institution</th><th>Status</th><th>Timeline</th><th></th></tr></thead><tbody id="focalRows">${rows||`<tr><td colspan="5" class="empty-state">No NTTC applications have been recorded yet.</td></tr>`}</tbody></table></div><div id="focalNoMatch" class="empty-state" hidden>No applications match the selected filter.</div></section>${TAESF.NTTC.QRScannerView.modal()}</main>`;
 }
 return Object.freeze({render});
})();
