"use strict";
NEXUS_SPECTRA.Services.CashierReportArchive=(()=>{
 const labels={RAAF:"Appendix 67 — RAAF",CASH_DISBURSEMENT:"Report of Cash Disbursements",CASH_RECEIPTS:"Appendix 29 — Cash Receipts Record",COLLECTION_DEPOSIT:"Appendix 26 — Report of Collections and Deposits"},required=["RAAF","CASH_DISBURSEMENT","CASH_RECEIPTS","COLLECTION_DEPOSIT"];
 function id(type,year,month,fund){return `COA-${type}-${year}-${String(month).padStart(2,"0")}-${String(fund||"ALL").replace(/\s+/g,"_")}`;} function get(type,year,month,fund){return NEXUS_SPECTRA.Repository.Cashier.reports().find(x=>x.reportId===id(type,year,month,fund))||null;}
 function baseTotals(type,year,month,fund){const start=new Date(`${year}-${String(month).padStart(2,"0")}-01T00:00:00`),end=new Date(start.getFullYear(),start.getMonth()+1,1);if(type==="RAAF"){const checks=NEXUS_SPECTRA.Repository.Cashier.checks().filter(x=>{const d=new Date(x.checkDate+"T00:00:00");return d>=start&&d<end&&(!fund||x.fund===fund)});return {records:checks.length,total:checks.reduce((n,x)=>n+Number(x.amount||0),0),released:checks.filter(x=>x.status==="RELEASED").length,unclaimed:checks.filter(x=>x.status==="UNCLAIMED").length,cancelled:checks.filter(x=>x.status==="CANCELLED").length};}if(type==="CASH_DISBURSEMENT"){const rows=NEXUS_SPECTRA.Repository.Cashier.cashAdvances().filter(x=>{const d=new Date(x.date+"T00:00:00");return d>=start&&d<end&&(!fund||x.fund===fund)});return {records:rows.length,total:rows.reduce((n,x)=>n+Number(x.amount||0),0),refunds:rows.reduce((n,x)=>n+Number(x.refunded||0),0),net:rows.reduce((n,x)=>n+Number(x.netDisbursed||0),0)};}const rows=NEXUS_SPECTRA.Repository.Cashier.collections().filter(x=>{const d=new Date(x.date+"T00:00:00");return d>=start&&d<end&&(!fund||x.fund===fund)});return {records:rows.length,total:rows.reduce((n,x)=>n+Number(x.collection||0),0),deposited:rows.reduce((n,x)=>n+Number(x.deposit||0),0),undeposited:rows.reduce((n,x)=>n+Number(x.undeposited||0),0)};}
 function savePreview(input){const reportId=id(input.type,input.year,input.month,input.fund),existing=get(input.type,input.year,input.month,input.fund),base=baseTotals(input.type,input.year,input.month,input.fund),adjust=Number(input.adjustment||0);if(adjust!==0&&(!String(input.overrideReason||"").trim()||!String(input.overrideBy||"").trim()))return {ok:false,errors:["A non-zero report adjustment requires a reason and the name of the requesting staff."]};const now=new Date().toISOString(),row={reportId,type:input.type,label:labels[input.type]||input.type,year:Number(input.year),month:Number(input.month),fund:input.fund||"",fundCluster:input.fundCluster||"",baseTotals:base,manualAdjustment:adjust,adjustedTotal:Number(base.total||0)+adjust,overrideReason:input.overrideReason||"",overrideBy:input.overrideBy||"",notes:input.notes||"",status:existing?.status||"SAVED_PREVIEW",generatedAt:existing?.generatedAt||now,updatedAt:now,dueDate:NEXUS_SPECTRA.Services.Cashier.coaMonthlyDueDate(Number(input.year),Number(input.month)),scanDocumentId:existing?.scanDocumentId||"",submittedToCOAAt:existing?.submittedToCOAAt||"",coaReceivingRef:existing?.coaReceivingRef||"",filedAt:existing?.filedAt||"",fileLocation:existing?.fileLocation||""};if(adjust!==0){
   const existingReq=NEXUS_SPECTRA.Repository.Admin.overrideRequests().find(x=>x.referenceNo===reportId&&x.status==="PENDING_ADMIN_APPROVAL");
   if(!existingReq){
     const req=NEXUS_SPECTRA.Services.AdminOverride.request({module:"CASHIER_REPORTS",requestType:"REPORT_ADJUSTMENT",referenceType:"REPORT",referenceNo:reportId,currentValue:Number(base.total||0),requestedValue:Number(base.total||0)+adjust,requestedBy:input.overrideBy,reason:input.overrideReason});
     if(req.ok){row.overrideRequestId=req.row.requestId;row.status="FOR_ADMIN_APPROVAL";}
   }
 }
 NEXUS_SPECTRA.Repository.Cashier.saveReport(row);return {ok:true,row};}
 async function attachScan(reportId,file,uploadedBy){if(!file)return {ok:false,errors:["Select the scanned signed report PDF/image."]};const r=NEXUS_SPECTRA.Repository.Cashier.reports().find(x=>x.reportId===reportId);if(!r)return {ok:false,errors:["Save the report preview first."]};const documentId=`COASCAN-${Date.now()}`,meta={documentId,transactionNo:"",batchId:"",reportId,docType:"COA_REPORT_SCAN",fileName:file.name,mimeType:file.type,fileSize:file.size,remarks:r.label,uploadedAt:new Date().toISOString(),uploadedBy:uploadedBy||"CASHIER"};await NEXUS_SHARED_DOCS.put(meta,file);r.scanDocumentId=documentId;r.scanUploadedAt=meta.uploadedAt;r.status=r.submittedToCOAAt?"SUBMITTED_TO_COA":"SCANNED_COPY_ATTACHED";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Cashier.saveReport(r);return {ok:true,row:r};}
 async function openScan(reportId){const r=NEXUS_SPECTRA.Repository.Cashier.reports().find(x=>x.reportId===reportId);if(!r?.scanDocumentId)return false;const d=await NEXUS_SHARED_DOCS.get(r.scanDocumentId);if(d)NEXUS_SHARED_DOCS.openBlob(d);return true;}
 function submitCOA(reportId,input){const r=NEXUS_SPECTRA.Repository.Cashier.reports().find(x=>x.reportId===reportId);if(!r)return {ok:false,errors:["Report not found."]};if(!r.scanDocumentId)return {ok:false,errors:["Attach the scanned signed/printed report before marking it submitted to COA."]};if(!input.receivingRef)return {ok:false,errors:["COA receiving/reference number is required."]};r.submittedToCOAAt=input.submittedAt||new Date().toISOString();r.coaReceivingRef=input.receivingRef;r.submittedBy=input.submittedBy||"";r.status="SUBMITTED_TO_COA";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Cashier.saveReport(r);return {ok:true,row:r};}
 function markFiled(reportId,input){const r=NEXUS_SPECTRA.Repository.Cashier.reports().find(x=>x.reportId===reportId);if(!r?.submittedToCOAAt)return {ok:false,errors:["Report must be submitted to COA before filing/archiving."]};r.filedAt=new Date().toISOString();r.fileLocation=input.fileLocation||"";r.status="FILED";r.updatedAt=r.filedAt;NEXUS_SPECTRA.Repository.Cashier.saveReport(r);return {ok:true,row:r};}
 function monthlyStatus(year,month,fund){return required.map(type=>{const r=get(type,year,month,fund),due=NEXUS_SPECTRA.Services.Cashier.coaMonthlyDueDate(year,month);return {type,label:labels[type],report:r,dueDate:due,overdue:!r?.submittedToCOAAt&&new Date()>new Date(due+"T23:59:59")};});}
 return Object.freeze({labels,required,get,baseTotals,savePreview,attachScan,openScan,submitCOA,markFiled,monthlyStatus});
})();