"use strict";
NEXUS_SPECTRA.Services.ComplianceClock=(()=>{
 const DAY=86400000;
 const RULES={
   ALLOWANCE_SIMILAR:{label:"Salaries / wages / allowances monitoring",aoDays:5,source:"COA Circular 97-002 §5.1.1",note:"System monitoring target. Circular states 5 days after each 15-day/end-of-month pay period; verify the correct basis date for the specific cash advance."},
   FIELD_COE:{label:"Field / Activity Current Operating Expenditure",aoDays:null,source:"COA Circular 97-002 §§4.4.2, 5.1.2",note:"Monthly Report of Disbursements within 5 days after month-end; year-end liquidation rule also applies."},
   PETTY_OPERATING:{label:"Petty Operating Expenses",aoDays:null,source:"COA Circular 97-002 §5.1.2",note:"Liquidation within 20 days after year-end, subject to replenishment during the year."},
   LOCAL_TRAVEL:{label:"Local Official Travel",aoDays:30,source:"COA Circular 97-002 §5.1.3",note:"30 days after return to permanent official station."},
   FOREIGN_TRAVEL:{label:"Foreign Official Travel",aoDays:60,source:"COA Circular 97-002 §5.1.3",note:"60 days after return to the Philippines."}
 };
 const dateOnly=v=>v?String(v).slice(0,10):"";const addDays=(v,d)=>{if(!v||d==null)return "";const x=new Date(dateOnly(v)+"T12:00:00");x.setDate(x.getDate()+Number(d));return x.toISOString().slice(0,10);};
 function daysBetween(a,b){if(!a||!b)return null;return Math.floor((new Date(dateOnly(b)+"T12:00:00")-new Date(dateOnly(a)+"T12:00:00"))/DAY);}
 function today(){return new Date().toISOString().slice(0,10);}
 function statusForDue(due,done){if(done)return {code:"COMPLETED",label:"Completed",days:0};if(!due)return {code:"NO_DUE_DATE",label:"Due date not set",days:null};const delta=daysBetween(today(),due);if(delta<0)return {code:"OVERDUE",label:`Overdue by ${Math.abs(delta)} day(s)`,days:delta};if(delta===0)return {code:"DUE_TODAY",label:"Due today",days:0};if(delta<=2)return {code:"DUE_SOON",label:`${delta} day(s) remaining`,days:delta};return {code:"ON_TRACK",label:`${delta} day(s) remaining`,days:delta};}
 function ensure(cashAdvanceId){const ca=NEXUS_SPECTRA.Repository.Cashier.cashAdvances().find(x=>x.cashAdvanceId===cashAdvanceId);if(!ca)return null;let r=NEXUS_SPECTRA.Repository.Compliance.cashAdvances().find(x=>x.cashAdvanceId===cashAdvanceId);if(!r){r={cashAdvanceId,transactionNo:ca.transactionNo,complianceType:"ALLOWANCE_SIMILAR",purposeServedAt:"",liquidationBasisDate:"",liquidationDueAt:"",liquidationSubmittedAt:"",liquidationSubmittedBy:"",accountingReceivedAt:"",accountingReceivedBy:"",accountingDeadlineAt:"",accountingVerifiedAt:"",jevRecordedAt:"",liquidationJevNo:"",coaSubmittedAt:"",coaReference:"",status:"FOR_DISTRIBUTION",remarks:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);}return r;}
 function saveMilestones(cashAdvanceId,input){const r=ensure(cashAdvanceId);if(!r)return {ok:false,errors:["Cash advance not found."]};const rule=RULES[input.complianceType||r.complianceType]||RULES.ALLOWANCE_SIMILAR;r.complianceType=input.complianceType||r.complianceType;r.purposeServedAt=input.purposeServedAt??r.purposeServedAt;r.liquidationBasisDate=input.liquidationBasisDate??r.liquidationBasisDate;r.liquidationDueAt=input.liquidationDueAt||((r.liquidationBasisDate||r.purposeServedAt)&&rule.aoDays!=null?addDays(r.liquidationBasisDate||r.purposeServedAt,rule.aoDays):r.liquidationDueAt);r.remarks=input.remarks??r.remarks;r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);return {ok:true,row:r};}
 function submitLiquidation(cashAdvanceId,input){const r=ensure(cashAdvanceId);if(!r)return {ok:false,errors:["Cash advance not found."]};if(!r.purposeServedAt&&!r.liquidationBasisDate)return {ok:false,errors:["Record the purpose-served/distribution completion or correct liquidation basis date first."]};r.liquidationSubmittedAt=input.submittedAt||new Date().toISOString();r.liquidationSubmittedBy=input.submittedBy||"";r.status="LIQUIDATION_SUBMITTED_TO_ACCOUNTING";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);return {ok:true,row:r};}
 function accountingReceive(cashAdvanceId,input){const r=ensure(cashAdvanceId);if(!r)return {ok:false,errors:["Cash advance not found."]};if(!r.liquidationSubmittedAt)return {ok:false,errors:["Liquidation must first be submitted by the Accountable Officer."]};r.accountingReceivedAt=input.receivedAt||new Date().toISOString();r.accountingReceivedBy=input.receivedBy||"";r.accountingDeadlineAt=addDays(r.accountingReceivedAt,10);r.status="ACCOUNTING_VERIFICATION";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);return {ok:true,row:r};}
 function recordJev(cashAdvanceId,input){const r=ensure(cashAdvanceId);if(!r)return {ok:false,errors:["Cash advance not found."]};if(!r.accountingReceivedAt)return {ok:false,errors:["Accounting receipt must be recorded before JEV/book recording."]};if(!input.jevNo)return {ok:false,errors:["Liquidation JEV number is required."]};r.accountingVerifiedAt=input.verifiedAt||r.accountingVerifiedAt||new Date().toISOString();r.jevRecordedAt=input.recordedAt||new Date().toISOString();r.liquidationJevNo=input.jevNo;r.status="ACCOUNTING_LIQUIDATED_RECORDED";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);return {ok:true,row:r};}
 function markCoa(cashAdvanceId,input){const r=ensure(cashAdvanceId);if(!r)return {ok:false,errors:["Cash advance not found."]};if(!r.jevRecordedAt)return {ok:false,errors:["Record the liquidation JEV/books entry before marking COA submission."]};if(!input.reference)return {ok:false,errors:["COA receiving/reference is required."]};r.coaSubmittedAt=input.submittedAt||new Date().toISOString();r.coaReference=input.reference;r.status="SUBMITTED_TO_COA";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.saveCashAdvance(r);return {ok:true,row:r};}
 function evaluate(cashAdvanceId){const r=ensure(cashAdvanceId),ca=NEXUS_SPECTRA.Repository.Cashier.cashAdvances().find(x=>x.cashAdvanceId===cashAdvanceId);if(!r||!ca)return null;const rule=RULES[r.complianceType]||RULES.ALLOWANCE_SIMILAR,ao=statusForDue(r.liquidationDueAt,r.liquidationSubmittedAt),acct=statusForDue(r.accountingDeadlineAt,r.jevRecordedAt);return {record:r,ca,rule,ao,accounting:acct};}
 function all(){return NEXUS_SPECTRA.Repository.Cashier.cashAdvances().map(x=>evaluate(x.cashAdvanceId)).filter(Boolean).sort((a,b)=>{const ax=a.ao.code==="OVERDUE"||a.accounting.code==="OVERDUE"?0:1,bx=b.ao.code==="OVERDUE"||b.accounting.code==="OVERDUE"?0:1;return ax-bx||String(a.record.liquidationDueAt||"9999").localeCompare(String(b.record.liquidationDueAt||"9999"));});}
 return Object.freeze({RULES,addDays,statusForDue,ensure,saveMilestones,submitLiquidation,accountingReceive,recordJev,markCoa,evaluate,all});
})();