"use strict";
NEXUS_SPECTRA.Services.NotificationCenter=(()=>{
 const READ_KEY="NEXUS:SPECTRA:notificationReadState";
 const loadRead=()=>{try{return JSON.parse(localStorage.getItem(READ_KEY)||"{}");}catch(_){return {};}};
 const saveRead=v=>localStorage.setItem(READ_KEY,JSON.stringify(v));
 const norm=s=>String(s||"").trim().toUpperCase().replace(/\s+/g," ");
 const now=()=>Date.now();
 function roleCode(name){const n=norm(name);if(n.includes("RECEIVING"))return "RECEIVING";if(n.includes("SCHOLARSHIP"))return "SCHOLARSHIP";if(n.includes("ACCOUNTING"))return "ACCOUNTING";if(n.includes("BUDGET"))return "BUDGET";if(n.includes("CASHIER"))return "CASHIER";if(n.includes("ADMIN"))return "ADMIN";return "ALL";}
 function ageDays(v){const t=new Date(v||Date.now()).getTime();return Math.max(0,Math.floor((now()-t)/86400000));}
 function readState(id,stored){if(stored)return !!stored.read;return !!loadRead()[id];}
 function make(o){return {severity:"info",createdAt:new Date().toISOString(),screen:"overview",...o};}
 function txItems(role){const rows=NEXUS_SPECTRA.Repository.Transactions?.all?.()||[],out=[];
  for(const x of rows){const age=ageDays(x.updatedAt||x.createdAt),base={createdAt:x.updatedAt||x.createdAt||new Date().toISOString(),ref:x.transactionNo};
   if(role==="RECEIVING"&&((x.physicalHolder==="RECEIVING")||["RECEIVED_AT_PO","FOR_COMPLIANCE"].includes(x.status)))out.push(make({...base,id:`DRV-RECEIVING-${x.transactionNo}-${x.status}`,severity:x.status==="FOR_COMPLIANCE"?"warning":age>=3?"warning":"info",title:x.status==="FOR_COMPLIANCE"?"Incomplete submission at Receiving":"Billing package at Receiving",message:`${x.tvi} · ${x.qualification}. ${age} day(s) since last update.`,screen:"registry"}));
   if(role==="SCHOLARSHIP"&&(["SCHOLARSHIP_REVIEW","FOR_COMPLIANCE"].includes(x.status)||x.physicalHolder==="SCHOLARSHIP"))out.push(make({...base,id:`DRV-SCHOLARSHIP-${x.transactionNo}-${x.status}`,severity:x.status==="FOR_COMPLIANCE"?"warning":age>=5?"warning":"info",title:x.status==="FOR_COMPLIANCE"?"TVI compliance pending":"Billing ready for Scholarship review",message:`${x.tvi} · ${x.qualification}. ${age} day(s) since last update.`,screen:x.status==="FOR_COMPLIANCE"?"review-queue":"review-queue"}));
   if(role==="ACCOUNTING"&&(["ACCOUNTING_REVIEW","ACCOUNTING_DV_JEV"].includes(x.status)||String(x.physicalHolder||"").startsWith("ACCOUNTING")))out.push(make({...base,id:`DRV-ACCOUNTING-${x.transactionNo}-${x.status}`,severity:age>=5?"warning":"info",title:x.status==="ACCOUNTING_DV_JEV"?"DV / JEV processing required":"Billing ready for Accounting review",message:`${x.tvi} · ${x.qualification}. ${age} day(s) since last update.`,screen:x.status==="ACCOUNTING_DV_JEV"?"dv-queue":"review-queue"}));
   if(role==="BUDGET"&&(x.status==="FOR_BUDGET_OBLIGATION"||x.physicalHolder==="BUDGET"))out.push(make({...base,id:`DRV-BUDGET-${x.transactionNo}-${x.status}`,severity:age>=3?"warning":"info",title:"For obligation processing",message:`${x.tvi} · ${x.qualification}. ${age} day(s) in Budget queue.`,screen:"queue"}));
   if(role==="CASHIER"&&(["FOR_CASHIER","PAYMENT_PROCESSING","PAYMENT_EXCEPTION","WITH_UNCLAIMED_CHECKS"].includes(x.status)||x.physicalHolder==="CASHIER"))out.push(make({...base,id:`DRV-CASHIER-${x.transactionNo}-${x.status}`,severity:/EXCEPTION|UNCLAIMED/.test(x.status)?"warning":age>=3?"warning":"info",title:/EXCEPTION|UNCLAIMED/.test(x.status)?"Cashier action / exception":"Approved payment ready for Cashier",message:`${x.tvi} · ${x.qualification}. ${age} day(s) since last update.`,screen:"payment-queue"}));
  }return out;
 }
 function tipItems(role){if(!window.NEXUS_TIP_SHARED)return [];const stored=NEXUS_TIP_SHARED.notifications();return stored.filter(n=>role==="SCHOLARSHIP"?n.audience==="SCHOLARSHIP":role==="ADMIN"?["SCHOLARSHIP"].includes(n.audience):false).map(n=>make({id:n.notificationId,source:"stored",stored:n,createdAt:n.createdAt,severity:/FOLLOWUP|COMPLIANCE|CONFLICT/i.test(n.type||"")?"warning":"info",title:n.title||"Notification",message:n.message||"",ref:n.ref||"",screen:/TIP/i.test(n.type||"")?"tip-requests":"overview"}));}
 function complianceItems(role){const out=[];if(!NEXUS_SPECTRA.Services.ComplianceClock?.all)return out;let rows=[];try{rows=NEXUS_SPECTRA.Services.ComplianceClock.all()||[];}catch(_){return out;}for(const x of rows){if(role==="ACCOUNTING"&&x.record?.liquidationSubmittedAt&&!x.record?.jevRecordedAt){const critical=x.accounting?.code==="OVERDUE";out.push(make({id:`DRV-ACCOUNTING-CA-${x.ca?.cashAdvanceId}-${x.accounting?.code}`,severity:critical?"critical":"warning",createdAt:x.record.accountingReceivedAt||x.record.liquidationSubmittedAt||new Date().toISOString(),title:critical?"Cash Advance Accounting deadline overdue":"Cash Advance liquidation clock active",message:`${x.ca?.cashAdvanceId||"Cash Advance"} · ${x.accounting?.label||"Accounting review pending"}`,ref:x.ca?.cashAdvanceId||"",screen:"ca-compliance"}));}
   if(role==="ADMIN"&&(["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.ao?.code)||["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.accounting?.code))){const critical=x.ao?.code==="OVERDUE"||x.accounting?.code==="OVERDUE";out.push(make({id:`DRV-ADMIN-CA-${x.ca?.cashAdvanceId}-${x.ao?.code}-${x.accounting?.code}`,severity:critical?"critical":"warning",createdAt:x.record?.updatedAt||x.record?.accountingReceivedAt||x.record?.purposeServedAt||new Date().toISOString(),title:critical?"Cash Advance compliance overdue":"Cash Advance compliance due soon",message:`${x.ca?.cashAdvanceId||"Cash Advance"} · AO: ${x.ao?.label||"—"} · Accounting: ${x.accounting?.label||"—"}`,ref:x.ca?.cashAdvanceId||"",screen:"compliance"}));}}
  return out;
 }
 function adminItems(role){if(role!=="ADMIN")return [];const out=[];try{for(const r of NEXUS_SPECTRA.Services.AdminOverride?.pending?.()||[])out.push(make({id:`DRV-ADMIN-APPROVAL-${r.requestId}`,severity:"warning",createdAt:r.requestedAt,title:"Approval request waiting",message:`${r.module} · ${r.referenceNo||r.requestId} · ${r.reason||r.requestType}`,ref:r.referenceNo||r.requestId,screen:"approvals"}));}catch(_){}return out;}
 function cashierControlItems(role){if(role!=="CASHIER")return [];const out=[];try{const checks=NEXUS_SPECTRA.Repository.Cashier?.checks?.()||[],u=checks.filter(x=>x.status==="UNCLAIMED");if(u.length)out.push(make({id:`DRV-CASHIER-UNCLAIMED-${u.length}`,severity:"warning",createdAt:u.map(x=>x.updatedAt||x.createdAt||x.checkDate||"").sort().at(-1)||new Date().toISOString(),title:`${u.length} unclaimed check${u.length===1?"":"s"} remain in custody`,message:"Review stale-date aging, release, cancellation, or replacement status.",screen:"accountable-forms"}));}catch(_){}return out;}
 function forRole(role){let items=[...tipItems(role),...txItems(role),...complianceItems(role),...adminItems(role),...cashierControlItems(role)];const read=loadRead();items=items.map(i=>({...i,read:i.source==="stored"?!!i.stored?.read:!!read[i.id]}));return items.sort((a,b)=>{const rank={critical:0,warning:1,info:2};return (rank[a.severity]-rank[b.severity])||String(b.createdAt||"").localeCompare(String(a.createdAt||""));});}
 function build(roleName){const role=roleCode(roleName);let items;if(role==="ALL"){const roles=["RECEIVING","SCHOLARSHIP","ACCOUNTING","BUDGET","CASHIER","ADMIN"],seen=new Set();items=[];for(const r of roles)for(const i of forRole(r)){if(seen.has(i.id))continue;seen.add(i.id);const route={RECEIVING:"receiving",SCHOLARSHIP:"scholarship",ACCOUNTING:"accounting",BUDGET:"budget",CASHIER:"cashier",ADMIN:"admin"}[r];items.push({...i,role:r,url:`workspaces/${route}/index.html${i.screen&&i.screen!=="overview"?`#${i.screen}`:""}`});}items.sort((a,b)=>({critical:0,warning:1,info:2}[a.severity]-({critical:0,warning:1,info:2}[b.severity]))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")));}else items=forRole(role);return {role,items,unread:items.filter(x=>!x.read).length,total:items.length};}
 function markRead(item){if(!item)return;if(item.source==="stored"&&window.NEXUS_TIP_SHARED){NEXUS_TIP_SHARED.markRead(item.id);return;}const r=loadRead();r[item.id]=new Date().toISOString();saveRead(r);}
 function markAll(roleName){const d=build(roleName);d.items.forEach(markRead);return build(roleName);}
 return Object.freeze({READ_KEY,roleCode,build,markRead,markAll});
})();