"use strict";
NEXUS_SPECTRA.Services.Print=(()=>{
 const esc=s=>(s??"").toString().replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 const peso=n=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n||0));
 const dt=v=>v?new Date(v).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"}):"";
 function routingSheet(row){
   const token=NEXUS_SPECTRA.Services.Transactions.qrToken(row),qr=NEXUS_SPECTRA.Utilities.QR.svg(token,155);
   const stages=["Receiving","Scholarship Review","Accounting Review","Budget / Obligation","Accounting – DV / JEV","Cashiering / Payment","Closed / Archives"];
   const stageRows=stages.map(s=>`<tr><td>${s}</td><td></td><td></td><td></td><td></td></tr>`).join("");
   const events=(row.events||[]).map(e=>`<tr><td>${esc(e.type.replaceAll("_"," "))}</td><td>${esc(e.by)}</td><td>${esc(dt(e.at))}</td><td>${esc(e.remarks||"")}</td></tr>`).join("");
   const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(row.transactionNo)} Routing Sheet</title><style>@page{size:A4 portrait;margin:10mm}body{font-family:Arial,sans-serif;font-size:9px;color:#000}.head{text-align:center}.head h1{font-size:14px;margin:4px}.summary{display:grid;grid-template-columns:1fr 165px;gap:12px;margin:10px 0}.qr{text-align:center}.qr small{display:block;font-size:7px}.box{border:1px solid #000;padding:8px}.kv{display:grid;grid-template-columns:135px 1fr;gap:4px}.kv b{font-weight:700}table{border-collapse:collapse;width:100%;margin-top:8px}th,td{border:1px solid #000;padding:4px;vertical-align:top}th{background:#eee}.big{font-size:12px;font-weight:700}.note{margin-top:8px;border:1px solid #000;padding:6px}.footer{margin-top:10px;font-size:7px;color:#333}</style></head><body><div class="head"><div>Republic of the Philippines</div><b>TECHNICAL EDUCATION AND SKILLS DEVELOPMENT AUTHORITY</b><div>TESDA Provincial Office – Albay</div><h1>SCHOLARSHIP BILLING ROUTING & TRACKING SHEET</h1></div><div class="summary"><div class="box"><div class="kv"><b>Transaction No.</b><span class="big">${esc(row.transactionNo)}</span><b>Receiving Control No.</b><span class="big">${esc(row.controlNo||"—")}</span><b>RQM</b><span>${esc(row.rqmCode||row.rqmNo)}</span><b>TVET Provider</b><span>${esc(row.tvi)}</span><b>Qualification</b><span>${esc(row.qualification)}</span><b>Claim</b><span>${esc(row.claimLabel)}</span><b>Claim Amount</b><span>${peso(row.claimAmount)}</span><b>Hard Copy Received</b><span>${esc(dt(row.receivedAt))}</span><b>Received By</b><span>${esc(row.receivedBy||"")}</span><b>Completeness</b><span>${esc((row.completenessStatus||"").replaceAll("_"," "))}</span></div></div><div class="qr">${qr}<small>QR token: ${esc(token)}</small><small>Scan only within authenticated NEXUS/SPECTRA.</small></div></div><table><thead><tr><th style="width:22%">Process Stage</th><th>Received By</th><th>Date / Time</th><th>Action / Findings</th><th>Released To / Date</th></tr></thead><tbody>${stageRows}</tbody></table><div class="note"><b>Deficiency / Compliance Notes:</b><br>${esc(row.deficiencyNote||"None at receiving.")}</div><h3>System Event Log at Time of Printing</h3><table><thead><tr><th>Event</th><th>By</th><th>Date / Time</th><th>Remarks</th></tr></thead><tbody>${events}</tbody></table><div class="footer">This routing sheet accompanies the physical scholarship billing folder. The NEXUS-SPECTRA electronic transaction log remains the official system tracking record. QR contains only a transaction token and no scholar/bank data.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;
   const w=window.open("","_blank");if(!w)throw new Error("Pop-up blocked.");w.document.open();w.document.write(html);w.document.close();
 }
 return Object.freeze({routingSheet});
})();