"use strict";
NEXUS_SPECTRA.Services.RCI=(()=>{
 const pad=(n,l=6)=>String(n).padStart(l,"0");
 function fromCheck(check){const tx=NEXUS_SPECTRA.Repository.Transactions.get(check.transactionNo),existing=NEXUS_SPECTRA.Repository.Cashier.rciEntries().find(x=>x.checkId===check.checkId);const row={rciEntryId:existing?.rciEntryId||`RCI-${check.checkId}`,checkId:check.checkId,sourceType:"SCHOLARSHIP_PAYMENT",sourceRef:check.transactionNo,checkDate:check.checkDate,checkNo:check.checkNo,dvPayrollNo:tx?.dvJev?.dvNo||"",dateReleased:check.releasedAt?check.releasedAt.slice(0,10):"",orsBursNo:tx?.budgetObligation?.no||"",responsibilityCenter:existing?.responsibilityCenter||"",payee:check.payee,uacsObjectCode:existing?.uacsObjectCode||"",natureOfPayment:existing?.natureOfPayment||`${tx?.claimLabel||"Scholarship payment"} – ${tx?.qualification||""}`,amount:Number(check.amount||0),tax:Number(existing?.tax||0),total:Number(check.amount||0)-Number(existing?.tax||0),fund:check.fund||tx?.scholarshipProgram||"",fundCluster:existing?.fundCluster||"01",status:check.status,rqmCode:tx?.rqmCode||tx?.rqmNo||"",scholarshipProgram:tx?.scholarshipProgram||"",trainingCost:Number(existing?.trainingCost||0),assessmentAmount:Number(existing?.assessmentAmount||0),tsfAmount:Number(existing?.tsfAmount||check.amount||0),hppeAmount:Number(existing?.hppeAmount||0),internetAmount:Number(existing?.internetAmount||0),adminCost:Number(existing?.adminCost||0),refundAllowance:Number(existing?.refundAllowance||0),remarks:existing?.remarks||"",createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};NEXUS_SPECTRA.Repository.Cashier.saveRciEntry(row);return row;}
 function syncChecks(){for(const ch of NEXUS_SPECTRA.Repository.Cashier.checks())fromCheck(ch);return all();}
 function all(){return NEXUS_SPECTRA.Repository.Cashier.rciEntries().sort((a,b)=>(a.checkDate+a.checkNo).localeCompare(b.checkDate+b.checkNo));}
 function saveManual(input){const errors=[],checkNo=String(input.checkNo||"").trim(),amount=Number(input.amount||0);if(!input.checkDate)errors.push("Check date is required.");if(!checkNo)errors.push("Check serial number is required.");if(!input.dvPayrollNo)errors.push("DV/Payroll number is required.");if(!input.payee)errors.push("Payee is required.");if(amount<=0)errors.push("Amount must be greater than zero.");if(!input.fund)errors.push("Fund/account is required.");if(checkNo&&!NEXUS_SPECTRA.Services.Cashier.activeSerial("CHECKS",input.fund,checkNo))errors.push(`Check No. ${checkNo} is not within a registered CHECKS accountable-form range for ${input.fund}.`);if(errors.length)return {ok:false,errors};const seq=NEXUS_SPECTRA.Repository.Cashier.rciEntries().length+1,row={rciEntryId:`RCI-MAN-${new Date().getFullYear()}-${pad(seq)}`,checkId:"",sourceType:input.sourceType||"OTHER_PAYMENT",sourceRef:input.sourceRef||"",checkDate:input.checkDate,checkNo,dvPayrollNo:input.dvPayrollNo,dateReleased:input.dateReleased||"",orsBursNo:input.orsBursNo||"",responsibilityCenter:input.responsibilityCenter||"",payee:input.payee,uacsObjectCode:input.uacsObjectCode||"",natureOfPayment:input.natureOfPayment||"",amount,tax:Number(input.tax||0),total:amount-Number(input.tax||0),fund:input.fund,fundCluster:input.fundCluster||"01",status:input.status||"ISSUED",rqmCode:input.rqmCode||"",scholarshipProgram:input.scholarshipProgram||"",trainingCost:Number(input.trainingCost||0),assessmentAmount:Number(input.assessmentAmount||0),tsfAmount:Number(input.tsfAmount||0),hppeAmount:Number(input.hppeAmount||0),internetAmount:Number(input.internetAmount||0),adminCost:Number(input.adminCost||0),refundAllowance:Number(input.refundAllowance||0),remarks:input.remarks||"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};NEXUS_SPECTRA.Repository.Cashier.saveRciEntry(row);return {ok:true,row};}
 function month(year,month,fund=""){syncChecks();return all().filter(x=>{const d=new Date(x.checkDate+"T00:00:00");return d.getFullYear()===Number(year)&&d.getMonth()+1===Number(month)&&(!fund||x.fund===fund)});}
 function summary(year,month,fund=""){const rows=month(year,month,fund);return {rows,count:rows.length,amount:rows.reduce((n,x)=>n+Number(x.amount||0),0),tax:rows.reduce((n,x)=>n+Number(x.tax||0),0),net:rows.reduce((n,x)=>n+Number(x.total||0),0),released:rows.filter(x=>!!x.dateReleased||x.status==="RELEASED").length,unreleased:rows.filter(x=>!x.dateReleased&&!["CANCELLED"].includes(x.status)).length,cancelled:rows.filter(x=>x.status==="CANCELLED").length};}
 return Object.freeze({fromCheck,syncChecks,all,saveManual,month,summary});
})();