"use strict";
NEXUS_SPECTRA.Services.Review=(()=>{
 const requiredChecklist=[
   {id:"RQM_MATCH",label:"RQM allocation, TVET Provider, qualification and claim type verified",source:"SYSTEM"},
   {id:"BILLING_STATEMENT",label:"Billing Statement is complete, signed and matches the system-computed amount",source:"DOCUMENT"},
   {id:"ATTENDANCE_SUMMARY",label:"Summary of Attendance is complete, signed and matches the finalized SAM snapshot",source:"DOCUMENT"},
   {id:"ATTENDANCE_SUPPORT",label:"BSRS attendance and applicable manual supporting attendance are complete",source:"DOCUMENT"},
   {id:"SCHOLAR_ROSTER",label:"Scholar roster and ULI information are reconciled with the billing package",source:"DOCUMENT"},
   {id:"BENEFIT_COMPUTATION",label:"TSF/benefit computation is consistent with the approved scholarship cost profile",source:"SYSTEM"},
   {id:"SIGNATURES",label:"Required signatures/certifications on school-submitted documents are complete",source:"DOCUMENT"},
   {id:"NO_DUPLICATE_PAYMENT",label:"No duplicate or previously paid claim is identified for the same component/tranche",source:"REVIEW"},
   {id:"WITHIN_RQM",label:"Claim amount is within the approved RQM allocation / available component ceiling",source:"SYSTEM"},
   {id:"DUE_DILIGENCE",label:"At least 20% scholar due-diligence verification has been completed",source:"SYSTEM"}
 ];
 function stableSeed(text){let h=2166136261;for(const ch of String(text||"")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
 function rng(seed){let s=seed>>>0;return ()=>{s=(Math.imul(1664525,s)+1013904223)>>>0;return s/4294967296;};}
 function scholars(tx){return tx?.snapshot?.allowance?.scholars||[];}
 function sample(tx){const list=scholars(tx);if(!list.length)return [];const count=Math.max(1,Math.ceil(list.length*.20)),arr=list.map((s,i)=>({...s,_i:i})),random=rng(stableSeed(tx.transactionNo));for(let i=arr.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr.slice(0,count).sort((a,b)=>a._i-b._i).map(s=>({key:s.key,name:s.name,email:s.email,status:"PENDING",method:"",contactedAt:"",verifiedBy:"",notes:""}));}
 function systemChecks(tx){
   const snap=tx?.snapshot||{},batch=snap.batch||{},attendance=snap.attendanceReports||[],vals=snap.validations||[],allow=snap.allowance||{},profile=snap.reportProfile||{};
   const uniqueDates=new Set(attendance.map(r=>r.attendanceDate).filter(Boolean));
   const scholars=allow.scholars||[],claimComputed=scholars.reduce((n,s)=>n+Number(s.earned||0),0);
   const checks={
     SNAPSHOT_HASH:{ok:!!tx.snapshotHash,detail:tx.snapshotHash?`Snapshot ${tx.snapshotHash}`:"No snapshot hash"},
     RQM_MATCH:{ok:!!(tx.rqmNo||tx.rqmCode)&&!!tx.tvi&&!!tx.qualification,detail:`${tx.rqmCode||tx.rqmNo} · ${tx.tvi} · ${tx.qualification}`},
     ATTENDANCE_DAYS:{ok:Number(batch.approvedTrainingDays||0)>0&&uniqueDates.size===Number(batch.approvedTrainingDays||0),detail:`${uniqueDates.size}/${batch.approvedTrainingDays||0} unique dated attendance reports`},
     NO_PENDING:{ok:scholars.length>0&&scholars.every(s=>s.isReady===true),detail:`${scholars.filter(s=>s.isReady).length}/${scholars.length} scholar allowance records ready`},
     CLAIM_MATCH:{ok:Math.abs(Number(tx.claimAmount||0)-claimComputed)<.01,detail:`Transaction ${Number(tx.claimAmount||0).toFixed(2)} vs SAM ${claimComputed.toFixed(2)}`},
     REPORT_DETAILS:{ok:!!profile.preparedBy&&!!profile.approvedBy,detail:profile.preparedBy?`Prepared by ${profile.preparedBy}; approved by ${profile.approvedBy||"—"}`:"School report signatory details missing"},
     ULI_COMPLETE:{ok:scholars.length>0&&Object.keys(profile.ulis||{}).length>=scholars.length&&scholars.every(s=>String(profile.ulis?.[s.key]||"").trim()),detail:`${scholars.filter(s=>String(profile.ulis?.[s.key]||"").trim()).length}/${scholars.length} ULIs populated`},
     BENEFIT_COMPUTATION:{ok:claimComputed>=0&&Number(batch.tsfRate||0)>0,detail:`TSF rate ${Number(batch.tsfRate||0).toFixed(2)}; claim ${claimComputed.toFixed(2)}`},
     WITHIN_RQM:{ok:Number(tx.claimAmount||0)<=Number(batch.maximumTsf||0)*Number(batch.numberOfSlots||0)+.01,detail:`Claim ${Number(tx.claimAmount||0).toFixed(2)} / current batch ceiling ${(Number(batch.maximumTsf||0)*Number(batch.numberOfSlots||0)).toFixed(2)}`}
   };
   return checks;
 }
 function ensure(transactionNo){
   const tx=NEXUS_SPECTRA.Repository.Transactions.get(transactionNo);if(!tx)return null;
   let row=NEXUS_SPECTRA.Repository.Reviews.get(transactionNo);
   if(!row){const now=new Date().toISOString();row={schemaVersion:"SPECTRA-SCH-REVIEW-1",transactionNo,reviewVersion:1,status:"DRAFT",reviewer:"",startedAt:now,updatedAt:now,checklist:requiredChecklist.map(c=>({...c,result:"PENDING",remarks:""})),dueDiligence:sample(tx),systemChecks:systemChecks(tx),deficiencies:[],complianceHistory:[]};NEXUS_SPECTRA.Repository.Reviews.save(row);}else{row.systemChecks=systemChecks(tx);const existing=new Set(row.dueDiligence.map(x=>x.key));sample(tx).forEach(x=>{if(!existing.has(x.key))row.dueDiligence.push(x);});NEXUS_SPECTRA.Repository.Reviews.save(row);}return row;
 }
 function updateChecklist(transactionNo,id,result,remarks=""){const row=ensure(transactionNo);if(!row)return {ok:false,errors:["Review not found."]};const item=row.checklist.find(x=>x.id===id);if(!item)return {ok:false,errors:["Checklist item not found."]};item.result=result;item.remarks=remarks;row.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Reviews.save(row);return {ok:true,row};}
 function updateDueDiligence(transactionNo,key,input){const row=ensure(transactionNo);if(!row)return {ok:false,errors:["Review not found."]};const item=row.dueDiligence.find(x=>x.key===key);if(!item)return {ok:false,errors:["Sample scholar not found."]};Object.assign(item,{method:input.method||"",status:input.status||"PENDING",notes:input.notes||"",verifiedBy:input.verifiedBy||"",contactedAt:input.contactedAt||new Date().toISOString()});row.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Reviews.save(row);return {ok:true,row};}
 function autoResults(row){const s=row.systemChecks||{};const map={RQM_MATCH:s.RQM_MATCH?.ok,BENEFIT_COMPUTATION:s.BENEFIT_COMPUTATION?.ok,WITHIN_RQM:s.WITHIN_RQM?.ok};for(const [id,ok] of Object.entries(map)){const x=row.checklist.find(c=>c.id===id);if(x&&x.result==="PENDING")x.result=ok?"PASSED":"FAILED";}const dd=row.checklist.find(c=>c.id==="DUE_DILIGENCE");if(dd)dd.result=row.dueDiligence.length>0&&row.dueDiligence.every(x=>x.status==="CONFIRMED")?"PASSED":"PENDING";return row;}
 function readiness(transactionNo){let row=ensure(transactionNo);const tx=NEXUS_SPECTRA.Repository.Transactions.get(transactionNo);if(!row||!tx)return {ok:false,errors:["Transaction/review not found."]};row=autoResults(row);NEXUS_SPECTRA.Repository.Reviews.save(row);const errors=[];if(!row.reviewer.trim())errors.push("Scholarship reviewer name is required.");const failedSystem=Object.entries(row.systemChecks).filter(([k,v])=>!v.ok).map(([k])=>k);if(failedSystem.length)errors.push(`System review has ${failedSystem.length} unresolved exception(s).`);const pending=row.checklist.filter(x=>x.result!=="PASSED");if(pending.length)errors.push(`${pending.length} checklist item(s) are not yet passed.`);const ddPending=row.dueDiligence.filter(x=>x.status!=="CONFIRMED");if(ddPending.length)errors.push(`${ddPending.length} due-diligence sample scholar(s) are not yet confirmed.`);return {ok:errors.length===0,errors,row,tx};}
 function saveReviewer(transactionNo,reviewer){const row=ensure(transactionNo);if(!row)return;row.reviewer=String(reviewer||"").trim();row.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Reviews.save(row);return row;}
 function returnForCompliance(transactionNo,input){const tx=NEXUS_SPECTRA.Repository.Transactions.get(transactionNo),row=ensure(transactionNo);if(!tx||!row)return {ok:false,errors:["Transaction not found."]};const note=String(input.note||"").trim(),by=String(input.by||row.reviewer||"").trim();const errors=[];if(!by)errors.push("Reviewer name is required.");if(!note)errors.push("Specify the deficiency/compliance requirement.");if(errors.length)return {ok:false,errors};const now=new Date().toISOString();row.reviewer=by;row.deficiencies.push({id:`DEF-${Date.now()}`,note,status:"OPEN",issuedAt:now,issuedBy:by,resolvedAt:"",resolution:""});row.status="FOR_COMPLIANCE";row.updatedAt=now;NEXUS_SPECTRA.Repository.Reviews.save(row);NEXUS_SPECTRA.Services.Transactions.addEvent(tx,"SCHOLARSHIP_DEFICIENCY","FOR_COMPLIANCE","SCHOLARSHIP",by,note);tx.actionRequiredBy="TVET_PROVIDER";tx.deficiencyNote=note;NEXUS_SPECTRA.Repository.Transactions.save(tx);return {ok:true,row,tx};}
 function recordCompliance(transactionNo,input){const tx=NEXUS_SPECTRA.Repository.Transactions.get(transactionNo),row=ensure(transactionNo);if(!tx||!row)return {ok:false,errors:["Transaction not found."]};const by=String(input.by||row.reviewer||"").trim(),note=String(input.note||"").trim();if(!by)return {ok:false,errors:["Receiving/reviewer name is required."]};const now=new Date().toISOString();const open=row.deficiencies.filter(x=>x.status==="OPEN");open.forEach(x=>{x.status="RESUBMITTED";x.resolvedAt=now;x.resolution=note||"Compliance documents received.";});row.complianceHistory.push({at:now,by,note:note||"Compliance documents received."});row.status="DRAFT";row.updatedAt=now;NEXUS_SPECTRA.Repository.Reviews.save(row);NEXUS_SPECTRA.Services.Transactions.addEvent(tx,"COMPLIANCE_RECEIVED","SCHOLARSHIP_REVIEW","SCHOLARSHIP",by,note||"Compliance documents received; scholarship review resumed.");tx.actionRequiredBy="SCHOLARSHIP";NEXUS_SPECTRA.Repository.Transactions.save(tx);return {ok:true,row,tx};}
 function verifyAndForward(transactionNo){const ready=readiness(transactionNo);if(!ready.ok)return ready;const {row,tx}=ready,now=new Date().toISOString();row.status="VERIFIED";row.verifiedAt=now;row.updatedAt=now;row.reviewSnapshot={systemChecks:JSON.parse(JSON.stringify(row.systemChecks)),checklist:JSON.parse(JSON.stringify(row.checklist)),dueDiligence:JSON.parse(JSON.stringify(row.dueDiligence))};NEXUS_SPECTRA.Repository.Reviews.save(row);NEXUS_SPECTRA.Services.Transactions.addEvent(tx,"SCHOLARSHIP_VERIFIED","ACCOUNTING_REVIEW","ACCOUNTING_REVIEW",row.reviewer,"Scholarship technical/documentary review completed. Immutable SAM snapshot and review record forwarded to Accounting Review.");tx.scholarshipReviewedAt=now;tx.scholarshipReviewedBy=row.reviewer;tx.actionRequiredBy="ACCOUNTING_REVIEW";NEXUS_SPECTRA.Repository.Transactions.save(tx);return {ok:true,row,tx};}
 return Object.freeze({requiredChecklist,ensure,systemChecks,sample,updateChecklist,updateDueDiligence,readiness,saveReviewer,returnForCompliance,recordCompliance,verifyAndForward});
})();