"use strict";
NEXUS_SPECTRA.Services.SubmissionPackage=(()=>{
 const DEFAULT_CHECKLIST=[
   {code:"DV",label:"Disbursement Voucher",required:true},
   {code:"JEV",label:"Journal Entry Voucher",required:true},
   {code:"RCI",label:"RCI / applicable check report",required:true},
   {code:"RD",label:"Report of Disbursements / Liquidation Report when applicable",required:false},
   {code:"PAYROLL",label:"Signed payroll / list of payees when applicable",required:false},
   {code:"SUPPORT",label:"Supporting documents required by transaction type",required:true}
 ];
 function create(input){const errors=[];if(!input.referenceNo)errors.push("Transaction/cash advance reference is required.");if(!input.dvNo)errors.push("DV number is required.");if(errors.length)return {ok:false,errors};const row={packageNo:NEXUS_SPECTRA.Repository.Compliance.nextPackageNo(),referenceType:input.referenceType||"TRANSACTION",referenceNo:input.referenceNo,transactionNo:input.transactionNo||"",cashAdvanceId:input.cashAdvanceId||"",dvNo:input.dvNo,jevNo:input.jevNo||"",rciNo:input.rciNo||"",rciPeriod:input.rciPeriod||"",physicalHolder:input.physicalHolder||"ACCOUNTING",transmittedToAccountingAt:input.transmittedToAccountingAt||"",transmittedToCOAAt:"",coaReference:"",returnedAt:"",deficiency:"",auditStatus:"NOT_SUBMITTED",scanDocumentId:"",checklist:DEFAULT_CHECKLIST.map(x=>({...x,required:input.requiredCodes?input.requiredCodes.includes(x.code):x.required,complete:false,remarks:""})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};NEXUS_SPECTRA.Repository.Compliance.savePackage(row);return {ok:true,row};}
 function get(no){return NEXUS_SPECTRA.Repository.Compliance.packages().find(x=>x.packageNo===no)||null;}
 function saveChecklist(no,items){const r=get(no);if(!r)return {ok:false,errors:["Package not found."]};r.checklist=r.checklist.map(x=>{const i=items.find(y=>y.code===x.code);return i?{...x,complete:!!i.complete,remarks:i.remarks||""}:x;});r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.savePackage(r);return {ok:true,row:r};}
 function readiness(r){const missing=r.checklist.filter(x=>x.required&&!x.complete);return {ready:missing.length===0,missing};}
 async function attachScan(no,file,uploadedBy){const r=get(no);if(!r)return {ok:false,errors:["Package not found."]};if(!file)return {ok:false,errors:["Select a scanned submission package."]};const documentId=`COAPKGSCAN-${Date.now()}`,meta={documentId,transactionNo:r.transactionNo||"",batchId:"",reportId:no,docType:"COA_SUBMISSION_PACKAGE",fileName:file.name,mimeType:file.type,fileSize:file.size,remarks:`COA submission package ${no}`,uploadedAt:new Date().toISOString(),uploadedBy:uploadedBy||""};await NEXUS_SHARED_DOCS.put(meta,file);r.scanDocumentId=documentId;r.updatedAt=meta.uploadedAt;NEXUS_SPECTRA.Repository.Compliance.savePackage(r);return {ok:true,row:r};}
 async function openScan(no){const r=get(no);if(!r?.scanDocumentId)return false;const d=await NEXUS_SHARED_DOCS.get(r.scanDocumentId);if(d)NEXUS_SHARED_DOCS.openBlob(d);return true;}
 function submitToCoa(no,input){const r=get(no);if(!r)return {ok:false,errors:["Package not found."]};const ready=readiness(r);if(!ready.ready)return {ok:false,errors:[`Complete required documents first: ${ready.missing.map(x=>x.label).join(", ")}`]};if(!r.scanDocumentId)return {ok:false,errors:["Attach the scanned complete submission package first."]};if(!input.reference)return {ok:false,errors:["COA receiving/reference is required."]};r.transmittedToCOAAt=input.submittedAt||new Date().toISOString();r.coaReference=input.reference;r.physicalHolder="COA";r.auditStatus="SUBMITTED_TO_COA";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.savePackage(r);return {ok:true,row:r};}
 function returnDeficiency(no,input){const r=get(no);if(!r)return {ok:false,errors:["Package not found."]};if(!input.deficiency)return {ok:false,errors:["Deficiency/finding is required."]};r.returnedAt=new Date().toISOString();r.deficiency=input.deficiency;r.physicalHolder=input.returnTo||"ACCOUNTING";r.auditStatus="RETURNED_DEFICIENCY";r.updatedAt=r.returnedAt;NEXUS_SPECTRA.Repository.Compliance.savePackage(r);return {ok:true,row:r};}
 function updateAudit(no,input){const r=get(no);if(!r)return {ok:false,errors:["Package not found."]};r.auditStatus=input.auditStatus||r.auditStatus;r.auditRemarks=input.remarks||"";r.updatedAt=new Date().toISOString();NEXUS_SPECTRA.Repository.Compliance.savePackage(r);return {ok:true,row:r};}
 return Object.freeze({DEFAULT_CHECKLIST,create,get,saveChecklist,readiness,attachScan,openScan,submitToCoa,returnDeficiency,updateAudit});
})();