"use strict";
TAESF.NTTC.FocalReviewService=(()=>{
  const S=TAESF.NTTC.Constants.STATUS,REVIEW_STATUSES=[S.SUBMITTED_FOR_INITIAL_REVIEW,S.UNDER_INITIAL_REVIEW,S.COMPLIANCE_SUBMITTED,S.UNDER_RE_REVIEW];
  function allApplications(){return TAESF.NTTC.ApplicationRepository.all().sort((a,b)=>String(b.updatedAt||b.submittedAt).localeCompare(String(a.updatedAt||a.submittedAt)));}
  function queue(){return allApplications().filter(a=>REVIEW_STATUSES.includes(a.status)).sort((a,b)=>String(a.submittedAt||a.updatedAt).localeCompare(String(b.submittedAt||b.updatedAt)));}
  function metrics(){const all=allApplications();return{total:all.length,needsReview:all.filter(a=>REVIEW_STATUSES.includes(a.status)).length,withDeficiency:all.filter(a=>a.status===S.WITH_DEFICIENCY).length,approvedHardcopy:all.filter(a=>[S.APPROVED_FOR_HARDCOPY_SUBMISSION,S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED].includes(a.status)).length,regional:all.filter(a=>[S.TRANSMITTED_TO_REGIONAL_OFFICE,S.REGIONAL_OFFICE_PROCESSING,S.RETRANSMITTED_TO_REGIONAL_OFFICE].includes(a.status)).length,readyRelease:all.filter(a=>[S.NTTC_RECEIVED_FROM_RO,S.CERTIFICATE_RECORDED,S.CERTIFICATE_READY_FOR_RELEASE].includes(a.status)).length};}
  function beginReview(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(app.status===S.SUBMITTED_FOR_INITIAL_REVIEW)TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.UNDER_INITIAL_REVIEW);else if(app.status===S.COMPLIANCE_SUBMITTED)TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.UNDER_RE_REVIEW);return TAESF.NTTC.ApplicationService.get(applicationId);}
  function saveDocumentFinding(applicationId,documentId,status,remarks,actor="CAC FOCAL",computation={}){
    if(!["COMPLIANT","DEFICIENT","FOR_VERIFICATION"].includes(status))throw new Error("Select a valid review finding.");const doc=TAESF.NTTC.DocumentRepository.findById(documentId);if(!doc)throw new Error("Document not found.");
    const existing=TAESF.NTTC.ScreeningRepository.byDocument(applicationId,documentId),row=existing||{screeningId:(crypto.randomUUID?crypto.randomUUID():"NTTCSCR-"+Date.now()+Math.random()),applicationId,documentId,requirementCode:""};
    row.findingStatus=status;row.remarks=String(remarks||"").trim();row.reviewedBy=actor;row.reviewedAt=new Date().toISOString();
    if(doc.documentType===TAESF.NTTC.Constants.DOCUMENT_TYPES.IWER_EVIDENCE){
      const mode=String(computation.mode||"");if(!["SYSTEM","ACTUAL"].includes(mode))throw new Error("Confirm the system-computed hours or choose verified actual hours for this IWER evidence.");
      row.hoursReviewMode=mode;row.systemRawHours=Number(doc.systemRawHours||0);row.systemEquivalentHours=Number(doc.systemEquivalentHours||0);row.modalityFactor=doc.modalityFactor;row.modality=doc.modality;row.modalityConfirmed=!!TAESF.NTTC.Constants.IWER_MODALITIES[doc.modality];
      if(!row.modalityConfirmed)throw new Error("The selected IWER modality is not recognized by the system.");
      if(mode==="SYSTEM"){row.approvedRawHours=Number(doc.systemRawHours||0);row.approvedEquivalentHours=Number(doc.systemEquivalentHours||0);row.hoursOverrideReason="";}
      else{const actual=Number(computation.actualHours);if(!actual||actual<=0)throw new Error("Enter the verified actual number of hours.");const factor=Number.isFinite(Number(doc.modalityFactor))?Number(doc.modalityFactor):1;row.approvedRawHours=actual;row.approvedEquivalentHours=actual*factor;row.hoursOverrideReason=String(computation.overrideReason||"").trim();if(!row.hoursOverrideReason)throw new Error("Enter the basis/reason for using verified actual hours instead of the system estimate.");}
      row.approvedEquivalentYears=row.approvedEquivalentHours/TAESF.NTTC.Constants.HOURS_PER_WORK_YEAR;row.hoursConfirmed=true;
    }
    return TAESF.NTTC.ScreeningRepository.save(row);
  }
  function createDeficiency(applicationId,documentId,finding,requiredAction,actor="CAC FOCAL"){if(!String(finding||"").trim())throw new Error("Enter the deficiency finding.");if(!String(requiredAction||"").trim())throw new Error("Enter the required action for the applicant.");const row=new TAESF.NTTC.DeficiencyModel({applicationId,documentId,finding:String(finding).trim(),requiredAction:String(requiredAction).trim()});TAESF.NTTC.DeficiencyRepository.save(row);const existing=TAESF.NTTC.ScreeningRepository.byDocument(applicationId,documentId);if(existing){existing.findingStatus="DEFICIENT";existing.remarks=String(finding).trim();existing.reviewedBy=actor;existing.reviewedAt=new Date().toISOString();TAESF.NTTC.ScreeningRepository.save(existing);}return row;}
  function issueDeficiencies(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId),open=TAESF.NTTC.DeficiencyRepository.openForApplication(applicationId);if(!open.length)throw new Error("Add at least one deficiency before returning the application to the applicant.");if(![S.UNDER_INITIAL_REVIEW,S.UNDER_RE_REVIEW].includes(app.status))throw new Error("Application must be under review before deficiencies can be issued.");TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.WITH_DEFICIENCY);return TAESF.NTTC.ApplicationService.get(applicationId);}
  function resolveDeficiency(applicationId,deficiencyId,actor="CAC FOCAL"){const d=TAESF.NTTC.DeficiencyRepository.findById(deficiencyId);if(!d||d.applicationId!==applicationId)throw new Error("Deficiency not found.");if(d.status!=="COMPLIED_PENDING_REVIEW")throw new Error("The applicant has not yet uploaded compliance for this finding.");const doc=d.complianceDocumentId&&TAESF.NTTC.DocumentRepository.findById(d.complianceDocumentId);if(!doc)throw new Error("Compliance document not found.");const finding=TAESF.NTTC.ScreeningRepository.byDocument(applicationId,doc.documentId);if(!finding||finding.findingStatus!=="COMPLIANT")throw new Error("Review the compliance document and mark it COMPLIANT before resolving this finding.");return TAESF.NTTC.DeficiencyRepository.close(deficiencyId,actor);}
  function approveForHardcopy(applicationId){const app=TAESF.NTTC.ApplicationService.get(applicationId);if(![S.UNDER_INITIAL_REVIEW,S.UNDER_RE_REVIEW].includes(app.status))throw new Error("Application must be under review before approval.");const open=TAESF.NTTC.DeficiencyRepository.openForApplication(applicationId);if(open.length)throw new Error("Resolve all open or pending-compliance findings before approving the application for hard-copy submission.");const docs=TAESF.NTTC.DocumentService.list(applicationId),screenings=TAESF.NTTC.ScreeningRepository.byApplication(applicationId);const reviewed=new Map(screenings.map(x=>[x.documentId,x]));const unreviewed=docs.filter(d=>reviewed.get(d.documentId)?.findingStatus!=="COMPLIANT");if(unreviewed.length)throw new Error("Review every current uploaded document and mark it COMPLIANT before approval.");const unconfirmedIwer=docs.filter(d=>d.documentType===TAESF.NTTC.Constants.DOCUMENT_TYPES.IWER_EVIDENCE&&!reviewed.get(d.documentId)?.hoursConfirmed);if(unconfirmedIwer.length)throw new Error("Confirm the IWER modality and hours computation for every IWER evidence before approval.");const modalityCheck=TAESF.NTTC.Computation.modalitySetCheck(app,docs);if(!modalityCheck.valid)throw new Error(modalityCheck.errors.join(" "));TAESF.NTTC.ApplicationService.changeStatus(applicationId,S.APPROVED_FOR_HARDCOPY_SUBMISSION);return TAESF.NTTC.ApplicationService.get(applicationId);}
  function applicantDeficiencies(applicationId){return TAESF.NTTC.DeficiencyRepository.openForApplication(applicationId);}function statusGroup(status){if(REVIEW_STATUSES.includes(status))return"review";if(status===S.WITH_DEFICIENCY)return"deficiency";if([S.APPROVED_FOR_HARDCOPY_SUBMISSION,S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED,S.APPLICANT_ARRIVED,S.HARDCOPY_UNDER_VERIFICATION].includes(status))return"hardcopy";if([S.HARDCOPY_RECEIVED,S.ORIGINALS_VERIFIED,S.FOR_PO_PROCESSING,S.FOR_PD_ENDORSEMENT,S.READY_FOR_RO_TRANSMITTAL].includes(status))return"provincial";if([S.TRANSMITTED_TO_REGIONAL_OFFICE,S.REGIONAL_OFFICE_PROCESSING,S.RETRANSMITTED_TO_REGIONAL_OFFICE,S.RETURNED_BY_REGIONAL_OFFICE,S.FOR_COMPLIANCE_WITH_RO_FINDING].includes(status))return"regional";if([S.NTTC_RECEIVED_FROM_RO,S.CERTIFICATE_RECORDED,S.CERTIFICATE_READY_FOR_RELEASE].includes(status))return"release";if([S.RELEASED,S.CLOSED].includes(status))return"closed";return"draft";}
  return Object.freeze({allApplications,queue,metrics,beginReview,saveDocumentFinding,createDeficiency,issueDeficiencies,resolveDeficiency,approveForHardcopy,applicantDeficiencies,statusGroup});
})();
