"use strict";
TAESF.NTTC.DocumentService=(()=>{
  const D=TAESF.NTTC.Constants.DOCUMENT_TYPES;
  const LABELS=Object.freeze({[D.NC_CERTIFICATE]:"National Certificate",[D.TMC_CERTIFICATE]:"Trainers Methodology Certificate I",[D.IWER_EVIDENCE]:"Industry Work Experience Evidence",[D.GOVERNMENT_ID]:"Government-issued ID",[D.OTHER_SUPPORTING]:"Other Supporting Document"});
  function validateFile(file){const errors=[];if(!file)errors.push("Select a file to upload.");else{if(!TAESF.NTTC.Constants.ACCEPTED_UPLOAD_MIME.includes(file.type))errors.push("Only PDF, JPG, JPEG, and PNG files are accepted.");if(file.size>TAESF.NTTC.Constants.MAX_UPLOAD_BYTES)errors.push("Each file must not exceed 10 MB.");}return{valid:errors.length===0,errors};}
  function computeIwer(data){if(!TAESF.NTTC.Constants.IWER_MODALITIES[data.modality])throw new Error("Select a recognized Industry Work Experience modality.");const estimate=TAESF.NTTC.Computation.estimateEvidence(data.fromDate,data.toDate,data.modality);if(!estimate.recognized)throw new Error("The selected IWER modality is not recognized by the system.");if(!estimate.rawHours)throw new Error("The inclusive dates do not produce a valid system estimate.");return estimate;}
  async function upload(applicationId,data,file){
    const check=validateFile(file);if(!check.valid)throw new Error(check.errors.join(" "));if(!data.documentType)throw new Error("Document type is required.");let estimate=null;
    if(data.documentType===D.IWER_EVIDENCE){if(!data.modality)throw new Error("Select the Industry Work Experience category that best describes this evidence.");if(!data.fromDate||!data.toDate)throw new Error("Enter the inclusive dates covered by this IWER evidence.");if(new Date(data.toDate)<new Date(data.fromDate))throw new Error("The IWER end date cannot be earlier than the start date.");estimate=computeIwer(data);}
    const meta=new TAESF.NTTC.DocumentModel({applicationId,documentType:data.documentType,modality:data.modality||"",title:data.title||LABELS[data.documentType]||"Supporting Document",fromDate:data.fromDate||"",toDate:data.toDate||"",claimedHours:estimate?estimate.equivalentHours:(data.claimedHours??""),systemRawHours:estimate?.rawHours||0,systemEquivalentHours:estimate?.equivalentHours||0,systemEquivalentYears:estimate?.equivalentYears||0,modalityFactor:estimate?.factor??null,computationPolicy:estimate?.policy||"",fileName:file.name,mimeType:file.type,sizeBytes:file.size,versionNo:data.versionNo||1,supersedesDocumentId:data.supersedesDocumentId||"",uploadPurpose:data.uploadPurpose||"INITIAL",deficiencyId:data.deficiencyId||""});
    await TAESF.NTTC.DocumentRepository.saveFile(meta.documentId,file);TAESF.NTTC.DocumentRepository.saveMeta(meta);return meta;
  }
  async function replaceSingle(applicationId,documentType,file){const existing=list(applicationId).filter(x=>x.documentType===documentType&&x.status!=="SUPERSEDED"),previous=existing[0]||null;const uploaded=await upload(applicationId,{documentType,title:LABELS[documentType],versionNo:previous?Number(previous.versionNo||1)+1:1,supersedesDocumentId:previous?.documentId||""},file);if(previous)TAESF.NTTC.DocumentRepository.markSuperseded(previous.documentId,uploaded.documentId);return uploaded;}
  async function uploadCompliance(applicationId,deficiency,sourceDocument,file){const base=sourceDocument||TAESF.NTTC.DocumentRepository.findById(deficiency.documentId);if(!base)throw new Error("The document related to this finding could not be located.");const uploaded=await upload(applicationId,{documentType:base.documentType,modality:base.modality||"",title:base.title||LABELS[base.documentType],fromDate:base.fromDate||"",toDate:base.toDate||"",versionNo:Number(base.versionNo||1)+1,supersedesDocumentId:base.documentId,uploadPurpose:"DEFICIENCY_COMPLIANCE",deficiencyId:deficiency.deficiencyId},file);TAESF.NTTC.DocumentRepository.markSuperseded(base.documentId,uploaded.documentId);return uploaded;}
  function normalizeLegacyIwer(row){if(row.documentType!==D.IWER_EVIDENCE)return row;if((!row.systemEquivalentHours||!row.systemRawHours)&&row.fromDate&&row.toDate&&row.modality&&TAESF.NTTC.Constants.IWER_MODALITIES[row.modality]){const x=TAESF.NTTC.Computation.estimateEvidence(row.fromDate,row.toDate,row.modality);row.systemRawHours=x.rawHours;row.systemEquivalentHours=x.equivalentHours;row.systemEquivalentYears=x.equivalentYears;row.modalityFactor=x.factor;row.computationPolicy=x.policy;row.claimedHours=x.equivalentHours;TAESF.NTTC.DocumentRepository.saveMeta(row);}return row;}
  function list(applicationId){return TAESF.NTTC.DocumentRepository.currentByApplication(applicationId).map(normalizeLegacyIwer);}function history(applicationId){return TAESF.NTTC.DocumentRepository.byApplication(applicationId).map(normalizeLegacyIwer);}async function remove(documentId){await TAESF.NTTC.DocumentRepository.deleteFile(documentId);TAESF.NTTC.DocumentRepository.removeMeta(documentId);return true;}
  function completeness(applicationId){const rows=list(applicationId),counts={};rows.forEach(x=>counts[x.documentType]=(counts[x.documentType]||0)+1);const missing=[];if(!counts[D.NC_CERTIFICATE])missing.push("Upload a readable copy of your National Certificate.");if(!counts[D.TMC_CERTIFICATE])missing.push("Upload a readable copy of your Trainers Methodology Certificate I.");if(!counts[D.IWER_EVIDENCE])missing.push("Upload at least one supporting document for your Industry Work Experience.");const app=TAESF.NTTC.ApplicationRepository.findById(applicationId);const modalityCheck=TAESF.NTTC.Computation.modalitySetCheck(app,rows);if(!modalityCheck.valid)missing.push(...modalityCheck.errors);return{complete:missing.length===0,missing,counts,total:rows.length,modalityCheck};}
  function label(type){return LABELS[type]||type;}function modalityGuide(code){return TAESF.NTTC.Constants.IWER_MODALITIES[code]||null;}
  return Object.freeze({validateFile,upload,replaceSingle,uploadCompliance,list,history,remove,completeness,label,modalityGuide,computeIwer});
})();
