"use strict";
NEXUS_SAM.Modules.Validation.View = (()=>{
 const esc=s=>(s??"").toString().replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 function renderBatchOptions(rows){const sel=document.getElementById("validationBatchId"),current=sel.value;sel.innerHTML=`<option value="">Select batch...</option>`+rows.map(r=>`<option value="${esc(r.batchId)}">${esc(r.rqmNo)} · ${esc(r.qualificationTitle)} · ${esc(r.tvi)}</option>`).join("");if(rows.some(r=>r.batchId===current))sel.value=current;}
 function summary(s){const set=(k,v)=>document.querySelectorAll(`[data-val-summary="${k}"]`).forEach(el=>el.textContent=v);set("records",s.records);set("bsrs",s.completeBsrs);set("manual",s.validatedManual);set("absent",s.absent);set("pending",s.pending);const ready=document.getElementById("validationReadyState");if(ready){ready.className=`readiness ${s.ready?"ready":"pending"}`;ready.textContent=s.ready?"Attendance Validation Complete — ready for allowance computation":"Resolve all pending attendance exceptions before allowance computation.";}}
 function badge(text,kind="neutral"){return `<span class="badge badge-${kind}">${esc((text||"").replaceAll("_"," "))}</span>`;}
 function table(rows){const body=document.getElementById("validationQueueBody");if(!rows.length){body.innerHTML=`<tr><td colspan="9" class="empty-state">No attendance exceptions for the selected batch.</td></tr>`;return;}body.innerHTML=rows.map(s=>{
   const status=s.validationStatus==="VALIDATED"?badge("VALIDATED","success"):badge("FOR VALIDATION","warning");
   const final=s.finalStatus==="ABSENT"?badge("ABSENT","danger"):(s.validation?badge(s.finalStatus,"success"):"—");
   return `<tr class="${s.validationStatus!=="VALIDATED"?"row-exception":""}"><td>${esc(s.attendanceDate||"—")}</td><td><strong>${esc(s.name)}</strong><br><small>Report ${esc(s.reportNumber||"—")}</small></td><td>${esc(s.bsrsTimeIn||"—")}</td><td>${esc(s.bsrsTimeOut||"—")}</td><td>${esc(s.finalTimeIn||"—")}</td><td>${esc(s.finalTimeOut||"—")}</td><td>${final}</td><td>${status}</td><td class="actions"><button type="button" class="btn btn-primary btn-sm" data-val-action="resolve" data-report="${esc(s.reportId)}" data-no="${s.no}">${s.validation?"Review":"Resolve"}</button>${s.validation?` <button type="button" class="btn btn-secondary btn-sm" data-val-action="clear" data-report="${esc(s.reportId)}" data-no="${s.no}">Reset</button>`:""}</td></tr>`;
 }).join("");}
 function openModal(source){const {report,scholar}=source,val=NEXUS_SAM.Modules.Validation.Repository.find(report.attendanceImportId,scholar.no);document.getElementById("validationReportId").value=report.attendanceImportId;document.getElementById("validationScholarNo").value=scholar.no;document.getElementById("validationModalTitle").textContent=`Validate ${scholar.name}`;document.getElementById("validationSourceSummary").innerHTML=`<strong>${esc(report.attendanceDate)}</strong> · Report ${esc(report.reportNumber)}<br><span>BSRS Time In: <strong>${esc(scholar.bsrsTimeIn||"—")}</strong> · Time Out: <strong>${esc(scholar.bsrsTimeOut||"—")}</strong> · Status: ${esc((source.timeIssue||scholar.attendanceStatus).replaceAll("_"," "))}</span>`;
   document.getElementById("validationResolution").value=val?.resolution||"PRESENT";document.getElementById("validationSource").value=val?.source||"MANUAL_ATTENDANCE_SHEET";document.getElementById("manualTimeIn").value=val?.manualTimeIn||"";document.getElementById("manualTimeOut").value=val?.manualTimeOut||"";document.getElementById("validationReason").value=val?.reason||"";document.getElementById("supportingReference").value=val?.supportingReference||"";document.getElementById("validatedBy").value=val?.validatedBy||localStorage.getItem("NEXUS-SAM:validatorName")||"";
   const anomaly=!!source.timeIssue;document.getElementById("manualTimeIn").disabled=!anomaly&&!!scholar.bsrsTimeIn;document.getElementById("manualTimeOut").disabled=!anomaly&&!!scholar.bsrsTimeOut;if(anomaly){document.getElementById("manualTimeIn").value=val?.manualTimeIn||"";document.getElementById("manualTimeOut").value=val?.manualTimeOut||"";}document.getElementById("validationModalErrors").hidden=true;document.getElementById("validationModal").hidden=false;document.body.classList.add("modal-open");}
 function closeModal(){document.getElementById("validationModal").hidden=true;document.body.classList.remove("modal-open");}
 function modalErrors(items=[]){const box=document.getElementById("validationModalErrors");box.hidden=!items.length;box.innerHTML=items.length?`<strong>Validation not saved:</strong><ul>${items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:"";}
 return Object.freeze({renderBatchOptions,summary,table,openModal,closeModal,modalErrors});
})();
