"use strict";
NEXUS_SPECTRA.AdminRole=(()=>{
 const esc=s=>(s??"").toString().replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 function counts(){const t=NEXUS_SPECTRA.Repository.Transactions.all();return {all:t.length,active:t.filter(x=>!["PAID","CLOSED"].includes(x.status)).length,receiving:t.filter(x=>x.physicalHolder==="RECEIVING").length,scholarship:t.filter(x=>x.physicalHolder==="SCHOLARSHIP").length,accounting:t.filter(x=>String(x.physicalHolder||"").startsWith("ACCOUNTING")).length,budget:t.filter(x=>x.physicalHolder==="BUDGET").length,cashier:t.filter(x=>x.physicalHolder==="CASHIER").length,exceptions:t.filter(x=>["FOR_COMPLIANCE","PAYMENT_EXCEPTION","WITH_UNCLAIMED_CHECKS"].includes(x.status)).length};}
 function renderApprovalsTo(id){const h=document.getElementById(id),rows=NEXUS_SPECTRA.Services.AdminOverride.pending();if(!h)return;h.innerHTML=rows.length?rows.map(x=>`<article class="override-card"><div><span>${esc(x.module)} · ${esc(x.requestType.replaceAll("_"," "))}</span><strong>${esc(x.referenceNo||x.requestId)}</strong><p>${esc(x.reason)}</p><small>Requested by ${esc(x.requestedBy)} · ${new Date(x.requestedAt).toLocaleString("en-PH")}</small></div><div><button class="role-primary" data-admin-approve="${esc(x.requestId)}">Approve</button> <button class="role-danger" data-admin-reject="${esc(x.requestId)}">Reject</button></div></article>`).join(""):'<div class="role-empty"><strong>No pending approvals.</strong><p>Requested overrides and report adjustments will appear here.</p></div>';}
 function renderComplianceTo(id){const h=document.getElementById(id),rows=NEXUS_SPECTRA.Services.ComplianceClock.all().filter(x=>["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.ao.code)||["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.accounting.code));if(!h)return;h.innerHTML=rows.length?rows.map(x=>`<div class="admin-action-row"><b>${x.ao.code==="OVERDUE"||x.accounting.code==="OVERDUE"?"OVERDUE":"DUE SOON"}</b><span>${esc(x.ca.cashAdvanceId)} · ${esc(x.ca.payee)}<small>AO: ${esc(x.ao.label)} · Accounting: ${esc(x.accounting.label)}</small></span></div>`).join(""):'<div class="role-empty">No due or overdue Cash Advance compliance clock.</div>';}
 function renderOverview(){const c=counts(),p=NEXUS_SPECTRA.Services.AdminOverride.pending(),comp=NEXUS_SPECTRA.Services.ComplianceClock.all().filter(x=>["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.ao.code)||["OVERDUE","DUE_TODAY","DUE_SOON"].includes(x.accounting.code));document.getElementById("adminKpis").innerHTML=`<article><span>Active Transactions</span><strong>${c.active}</strong><small>all processes</small></article><article class="${p.length?'warn':''}"><span>Pending Approvals</span><strong>${p.length}</strong><small>override / adjustment</small></article><article class="${c.exceptions?'warn':''}"><span>Exceptions</span><strong>${c.exceptions}</strong><small>compliance / payment</small></article><article class="${comp.length?'critical':''}"><span>Compliance Aging</span><strong>${comp.length}</strong><small>due / overdue</small></article>`;document.getElementById("adminProcesses").innerHTML=[["Receiving",c.receiving,"receiving"],["Scholarship",c.scholarship,"scholarship"],["Accounting",c.accounting,"accounting"],["Budget",c.budget,"budget"],["Cashier",c.cashier,"cashier"]].map(x=>`<button class="module-card" data-admin-process="${x[2]}"><strong>${x[0]}</strong><small>${x[1]} transaction(s) currently held</small></button>`).join("");renderApprovalsTo("adminApprovals");renderComplianceTo("adminCompliance");}
 function renderProcess(name){const h=document.getElementById("adminProcessResults"),all=NEXUS_SPECTRA.Repository.Transactions.all(),pred={receiving:x=>x.physicalHolder==="RECEIVING",scholarship:x=>x.physicalHolder==="SCHOLARSHIP",accounting:x=>String(x.physicalHolder||"").startsWith("ACCOUNTING"),budget:x=>x.physicalHolder==="BUDGET",cashier:x=>x.physicalHolder==="CASHIER"}[name]||(()=>true),rows=all.filter(pred);document.getElementById("adminProcessTitle").textContent=name.charAt(0).toUpperCase()+name.slice(1);h.innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Transaction</th><th>RQM</th><th>TVI / Qualification</th><th>Status</th><th>Holder</th><th>Updated</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.transactionNo)}</strong></td><td>${esc(r.rqmCode||r.rqmNo)}</td><td>${esc(r.tvi)}<small>${esc(r.qualification)}</small></td><td><span class="role-status">${esc(r.status.replaceAll("_"," "))}</span></td><td>${esc(r.physicalHolder)}</td><td>${r.updatedAt?new Date(r.updatedAt).toLocaleString("en-PH"):"—"}</td></tr>`).join("")}</tbody></table></div>`:'<div class="role-empty">No transactions currently held by this process.</div>';NEXUS_SPECTRA.Controllers.RoleRouter.show("process-monitor");}
 function decide(id,decision){const reviewedBy=prompt("Head of Admin / Approver name:");if(reviewedBy===null)return;const remarks=prompt("Decision remarks / conditions:",decision==="APPROVED"?"Approved":"Rejected")||"";const r=NEXUS_SPECTRA.Services.AdminOverride.decide(id,{decision,reviewedBy,remarks});if(!r.ok)return NEXUS_SPECTRA.Views.App.notify(r.errors[0],"error");NEXUS_SPECTRA.Views.App.notify(`Request ${decision.toLowerCase()}.`,"success");renderOverview();renderApprovalsTo("adminApprovalsFull");}
 function history(){const rows=NEXUS_SPECTRA.Services.AdminOverride.recent(),h=document.getElementById("adminHistory");h.innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Module</th><th>Reference</th><th>Request</th><th>Status</th><th>Reviewed By</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.requestedAt).toLocaleString("en-PH")}</td><td>${esc(x.module)}</td><td>${esc(x.referenceNo||x.requestId)}</td><td>${esc(x.requestType.replaceAll("_"," "))}<small>${esc(x.reason)}</small></td><td><span class="role-status">${esc(x.status.replaceAll("_"," "))}</span></td><td>${esc(x.reviewedBy||"—")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="role-empty">No override history.</div>';}
 function click(e){const p=e.target.closest("[data-admin-process]");if(p)return renderProcess(p.dataset.adminProcess);const a=e.target.closest("[data-admin-approve]");if(a)return decide(a.dataset.adminApprove,"APPROVED");const r=e.target.closest("[data-admin-reject]");if(r)return decide(r.dataset.adminReject,"REJECTED");}
 function initialize(){document.addEventListener("click",click);renderOverview();renderApprovalsTo("adminApprovalsFull");renderComplianceTo("adminComplianceFull");history();}
 return Object.freeze({initialize,renderOverview,renderApprovalsTo,renderComplianceTo,history});
})();