"use strict";
TAESF.NTTC.ApplicationService = (()=>{
  function create(data){const app=new TAESF.NTTC.ApplicationModel(data);return TAESF.NTTC.ApplicationRepository.save(app);}
  function get(applicationId){const app=TAESF.NTTC.ApplicationRepository.findById(applicationId);if(!app)throw new Error("NTTC application not found.");return app;}
  function forApplicant(applicantId){return TAESF.NTTC.ApplicationRepository.byApplicant(applicantId);}
  function saveDraft(applicationId,patch){const app=get(applicationId);if(![TAESF.NTTC.Constants.STATUS.DRAFT,TAESF.NTTC.Constants.STATUS.READY_FOR_ONLINE_SUBMISSION].includes(app.status))throw new Error("This application can no longer be edited as a draft.");["qualificationCode","qualificationTitle","sector","credentials","applicationDetails"].forEach(k=>{if(Object.prototype.hasOwnProperty.call(patch,k))app[k]=patch[k];});app.version=Number(app.version||1)+1;return TAESF.NTTC.ApplicationRepository.save(app);}
  function checkPrerequisites(applicationId){const app=get(applicationId);const result=TAESF.NTTC.PrerequisiteValidator.validate(app);app.prerequisiteCheck={valid:result.valid,errors:result.errors,checkedAt:new Date().toISOString()};if(result.valid&&app.status===TAESF.NTTC.Constants.STATUS.DRAFT)app.status=TAESF.NTTC.Constants.STATUS.READY_FOR_ONLINE_SUBMISSION;if(!result.valid&&app.status===TAESF.NTTC.Constants.STATUS.READY_FOR_ONLINE_SUBMISSION)app.status=TAESF.NTTC.Constants.STATUS.DRAFT;app.version=Number(app.version||1)+1;TAESF.NTTC.ApplicationRepository.save(app);return result;}
  function submitForInitialReview(applicationId){const app=get(applicationId);if(app.status!==TAESF.NTTC.Constants.STATUS.READY_FOR_ONLINE_SUBMISSION)throw new Error("The application is not ready for online submission.");const prereq=TAESF.NTTC.PrerequisiteValidator.validate(app);if(!prereq.valid)throw new Error(prereq.errors.join(" "));const docs=TAESF.NTTC.DocumentService.completeness(applicationId);if(!docs.complete)throw new Error(docs.missing.join(" "));TAESF.NTTC.Workflow.assertTransition(app.status,TAESF.NTTC.Constants.STATUS.SUBMITTED_FOR_INITIAL_REVIEW);if(!app.controlNumber)app.controlNumber=TAESF.NTTC.ControlNumberService.next(new Date().getFullYear());app.status=TAESF.NTTC.Constants.STATUS.SUBMITTED_FOR_INITIAL_REVIEW;app.submittedAt=new Date().toISOString();app.version=Number(app.version||1)+1;return TAESF.NTTC.ApplicationRepository.save(app);}
  function changeStatus(applicationId,nextStatus){const app=get(applicationId);TAESF.NTTC.Workflow.assertTransition(app.status,nextStatus);app.status=nextStatus;app.version=Number(app.version||1)+1;TAESF.NTTC.ApplicationRepository.save(app);return app;}
  return Object.freeze({create,get,forApplicant,saveDraft,checkPrerequisites,submitForInitialReview,changeStatus});
})();
