"use strict";
NEXUS_SAM.Modules.Batch.View = (()=>{
 const money=(v)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(v||0));
 function input(){const selected=document.getElementById("approvedRqmSelect")?.value||document.getElementById("rqmNo").value;return {batchId:document.getElementById("batchId").value,rqmNo:selected,rqmCode:selected,scholarshipProgram:document.getElementById("scholarshipProgram").value,implementationType:document.getElementById("implementationType").value,qualificationCostMasterId:document.getElementById("qualificationCostMasterId").value,tvi:(NEXUS_SAM.Modules.RQM?.get?.(selected)?.tvi||document.getElementById("tvi").value),trainer:document.getElementById("trainer").value,trainingStartDate:document.getElementById("trainingStartDate").value,trainingEndDate:document.getElementById("trainingEndDate").value,numberOfSlots:document.getElementById("numberOfSlots").value};}
 function errors(items=[]){const box=document.getElementById("formErrors");box.hidden=!items.length;box.innerHTML=items.length?`<strong>Please correct:</strong><ul>${items.map(x=>`<li>${x}</li>`).join("")}</ul>`:"";}
 function reset(){document.getElementById("batchForm").reset();document.getElementById("batchId").value="";document.getElementById("scholarshipProgram").value="TWSP";document.getElementById("implementationType").value="REGULAR";errors([]);NEXUS_SAM.Modules.CostMaster.Controller.refresh();NEXUS_SAM.Modules.CostMaster.View.showQualification(null);document.getElementById("formTitle").textContent="Create Scholarship Batch";}
 function fill(r){document.getElementById("batchId").value=r.batchId;["rqmNo","rqmCode","scholarshipProgram","implementationType","qualificationCostMasterId","tvi","trainer","trainingStartDate","trainingEndDate","numberOfSlots"].forEach(k=>document.getElementById(k).value=r[k]??"");document.getElementById("formTitle").textContent=`Edit ${r.batchId}`;NEXUS_SAM.Modules.CostMaster.View.showQualification(NEXUS_SAM.Modules.CostMaster.Service.get(r.qualificationCostMasterId));window.scrollTo({top:0,behavior:"smooth"});}
 function render(rows){const body=document.getElementById("batchTableBody");body.innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${r.batchId}</strong><br><small>${r.rqmNo}${r.rqmCode?` · ${r.rqmCode}`:""}</small></td><td>${r.scholarshipProgram}<br><small>${r.implementationType}</small></td><td><strong>${r.qualificationTitle}</strong><br><small>${r.socCode}</small></td><td>${r.tvi}</td><td>${r.approvedTrainingHours}h / ${r.approvedTrainingDays}d</td><td>${money(r.maximumTsf)}</td><td>${r.numberOfSlots}</td><td><span class="badge badge-neutral">${r.status}</span></td><td class="actions"><button class="btn btn-secondary btn-sm" data-action="open" data-id="${r.batchId}">Open Workflow</button> <button class="btn btn-secondary btn-sm" data-action="edit" data-id="${r.batchId}">Edit</button> <button class="btn btn-danger btn-sm" data-action="remove" data-id="${r.batchId}">Remove</button></td></tr>`).join(""):`<tr><td colspan="9" class="empty-state">No scholarship batches yet.</td></tr>`;}
 return Object.freeze({input,errors,reset,fill,render});})();
