"use strict";
TAESF.NTTC.SubmittedView=(()=>{
  function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));}
  function detail(application){
    const S=TAESF.NTTC.Constants.STATUS,stage=TAESF.NTTC.Workflow.applicantStage(application.status);
    if(application.status===S.APPROVED_FOR_HARDCOPY_SUBMISSION)return{eyebrow:"ONLINE REVIEW COMPLETED",title:stage,text:"Your online documents were reviewed and found complete and proper for hard-copy submission. This is not approval or issuance of the NTTC. You may now prepare the generated CoCIE Application Form (Form A) for notarization and wait for the submission schedule from the CAC focal.",tone:"approved",event:"Approved for Hard-Copy Submission",eventText:"Generate Form A, review all entries, print it and have it notarized before the scheduled physical submission."};
    if([S.SUBMISSION_SCHEDULED,S.APPOINTMENT_CONFIRMED].includes(application.status))return{eyebrow:"HARD-COPY SUBMISSION SCHEDULED",title:stage,text:"Your CAC focal has assigned a schedule for submission of the notarized Form A and hard-copy supporting documents. Review the schedule below and confirm it in the portal.",tone:"approved",event:"Submission Schedule Assigned",eventText:"Prepare the prescribed Form A, have it notarized, and bring the required hard copies and originals on the assigned schedule."};
    if([S.APPLICANT_ARRIVED,S.HARDCOPY_UNDER_VERIFICATION].includes(application.status))return{eyebrow:"PHYSICAL SUBMISSION IN PROGRESS",title:stage,text:"Your arrival at the TESDA Albay Provincial Office has been recorded. The CAC focal is verifying the notarized Form A, hard-copy documents, and originals presented.",tone:"review",event:"Applicant Check-In Recorded",eventText:"Please remain available while the CAC focal completes the physical-document verification."};
    if([S.COMPLIANCE_SUBMITTED,S.UNDER_RE_REVIEW].includes(application.status))return{eyebrow:"COMPLIANCE RECEIVED",title:"Submitted for Re-Review",text:"Your documentary compliance has been submitted to the CAC focal for re-review.",tone:"review",event:"Compliance Submitted",eventText:"The CAC focal will review your corrected or additional documents. No further action is needed unless another finding is issued."};
    if([S.TRANSMITTED_TO_REGIONAL_OFFICE,S.RETRANSMITTED_TO_REGIONAL_OFFICE,S.REGIONAL_OFFICE_PROCESSING].includes(application.status))return{eyebrow:"PROVINCIAL PROCESSING COMPLETED",title:stage,text:"Your application has been transmitted to the TESDA Regional Office for review and processing. Transmission does not mean that the NTTC has already been approved or issued.",tone:"regional",event:"Submitted to Regional Office",eventText:"Please monitor this page. The Provincial Office will update the record when the certificate or a Regional Office finding is received."};
    if([S.NTTC_RECEIVED_FROM_RO,S.CERTIFICATE_RECORDED,S.CERTIFICATE_READY_FOR_RELEASE].includes(application.status))return{eyebrow:"CERTIFICATE UPDATE",title:"Certificate Ready for Release",text:"The Provincial Office has received and recorded the certificate. Please follow the release instructions provided by the CAC focal and present your claim stub or valid identification as required.",tone:"ready",event:"Certificate Ready",eventText:"The scanned internal record of the NTTC is not displayed in the applicant portal."};
    if([S.RELEASED,S.CLOSED].includes(application.status))return{eyebrow:"APPLICATION COMPLETED",title:"Released",text:"The NTTC has been released and the application record is complete.",tone:"ready",event:"Certificate Released",eventText:"This application is now part of your completed application history."};
    if([S.HARDCOPY_RECEIVED,S.ORIGINALS_VERIFIED,S.FOR_PO_PROCESSING,S.FOR_PD_ENDORSEMENT,S.READY_FOR_RO_TRANSMITTAL].includes(application.status))return{eyebrow:"HARD COPY RECEIVED",title:stage,text:"Your hard-copy application has been received by the TESDA Albay Provincial Office and is being processed for endorsement/transmittal.",tone:"review",event:"Hard Copy Received",eventText:"The next major applicant-visible update will be when the application is transmitted to the Regional Office."};
    return{eyebrow:"ONLINE SUBMISSION RECEIVED",title:stage,text:"Your application has been sent to the TESDA Albay CAC focal for initial documentary review.",tone:"review",event:"Submitted for Initial Review",eventText:"The online copies are queued for CAC focal review. This does not constitute approval or issuance of an NTTC."};
  }
  function render(applicant,application){
    const d=detail(application),formAvailable=TAESF.NTTC.CoCIEFormService.canGenerate(application);
    return `<main class="application-shell"><header class="application-topbar"><div class="app-brand"><img src="../../assets/Logo.png" alt="TESDA Logo"><div><span>NEXUS • NTTC APPLICATION MONITORING</span><strong>TESDA Albay Provincial Office</strong></div></div><div class="applicant-menu"><div class="applicant-meta"><strong>${esc(applicant.fullName||"")}</strong><span>${esc(applicant.learnerId||"")}</span></div><button id="myApplications" class="secondary icon-button">My Applications</button><button id="logoutApplicant" class="secondary icon-button">Exit</button></div></header>
    <section class="tracking-shell"><div class="tracking-hero tracking-${esc(d.tone)}"><img class="nexus-watermark" src="../../assets/Logo.png" alt="" aria-hidden="true"><span class="eyebrow light">${esc(d.eyebrow)}</span><h1>${esc(d.title)}</h1><p>${esc(d.text)}</p><div class="control-card"><span>Application Control Number</span><strong>${esc(application.controlNumber)}</strong><small>Use this number whenever you contact the TESDA Albay CAC focal about this application.</small></div></div>
    <section class="applicant-process-panel"><div class="portal-panel-head"><div><span class="eyebrow">APPLICATION JOURNEY</span><h2>Your NTTC process</h2><p>The highlighted stage shows where this application is now.</p></div></div>${TAESF.NTTC.ApplicantPortalView.processHtml(application)}</section>
    <div id="applicantAppointmentMount"></div>${formAvailable?`<section class="form-a-action-card"><div><span class="eyebrow">FORM A • CoCIE APPLICATION FORM</span><h2>Generate your notarization form</h2><p>NEXUS will prepare Form A using your approved online application data and IWER evidence list. Review all entries before printing and notarization.</p></div><button id="generateFormA" class="primary modern-primary" type="button">Generate / Print Form A <span>↗</span></button></section>`:`<section class="form-a-action-card locked"><div><span class="eyebrow">FORM A</span><h2>Form generation is not yet available</h2><p>The CoCIE Application Form becomes available after the CAC focal completes the initial online review and approves the application for hard-copy submission.</p></div></section>`}
    <div class="tracking-card"><div class="timeline-dot active"></div><div><span>${new Date(application.updatedAt||application.submittedAt).toLocaleString()}</span><h3>${esc(d.event)}</h3><p>${esc(d.eventText)}</p></div></div><div class="policy-note"><strong>Important:</strong> ${TAESF.NTTC.Constants.DISCLAIMER}</div></section></main>`;
  }
  return Object.freeze({render,detail});
})();
