"use strict";
NEXUS_SAM.Modules.Validation.Service = (()=>{
 const clean=v=>(v??"").toString().trim();
 function getSource(reportId,scholarNo){const report=NEXUS_SAM.Modules.Attendance.Repository.all().find(r=>r.attendanceImportId===reportId);if(!report)return null;const scholar=report.scholars.find(s=>Number(s.no)===Number(scholarNo));return scholar?{report,scholar}:null;}
 function issueFor(s){return NEXUS_SAM.Modules.Allowance.Service?.timeIssue?.(s.bsrsTimeIn,s.bsrsTimeOut)||"";}
 function resolvedScholar(report,scholar){const val=NEXUS_SAM.Modules.Validation.Repository.find(report.attendanceImportId,scholar.no),issue=issueFor(scholar),isComplete=scholar.attendanceStatus==="COMPLETE_BSRS"&&!issue;return {...scholar,reportId:report.attendanceImportId,batchId:report.batchId,attendanceDate:report.attendanceDate,reportNumber:report.reportNumber,fileName:report.fileName,validation:val,timeIssue:issue,finalTimeIn:val?.finalTimeIn||scholar.bsrsTimeIn||"",finalTimeOut:val?.finalTimeOut||scholar.bsrsTimeOut||"",finalStatus:val?.finalStatus||(isComplete?"PRESENT_BSRS":"FOR_VALIDATION"),validationStatus:val?"VALIDATED":(isComplete?"VALIDATED":"FOR_VALIDATION")};}
 function queue(batchId){if(!batchId)return [];return NEXUS_SAM.Modules.Attendance.Repository.byBatch(batchId).flatMap(r=>r.scholars.map(s=>resolvedScholar(r,s))).filter(s=>s.attendanceStatus!=="COMPLETE_BSRS"||s.timeIssue||s.validation);}
 function save(input){const src=getSource(input.attendanceImportId,input.scholarNo);if(!src)return {ok:false,errors:["The source BSRS attendance record could not be found."]};const {report,scholar}=src,resolution=clean(input.resolution),source=clean(input.source),reason=clean(input.reason),validatedBy=clean(input.validatedBy),issue=issueFor(scholar);const errors=[];if(!resolution)errors.push("Select a validation resolution.");if(resolution!=="ABSENT"&&!source)errors.push("Select the supporting attendance source.");if(!reason)errors.push("Enter the reason or validation remarks.");if(!validatedBy)errors.push("Enter the registrar/validator name.");let manualTimeIn=clean(input.manualTimeIn),manualTimeOut=clean(input.manualTimeOut);let finalTimeIn="",finalTimeOut="",finalStatus="";if(resolution==="ABSENT"){manualTimeIn="";manualTimeOut="";finalStatus="ABSENT";}else{const needsOverride=!!issue;finalTimeIn=needsOverride?(manualTimeIn||scholar.bsrsTimeIn):(scholar.bsrsTimeIn||manualTimeIn);finalTimeOut=needsOverride?(manualTimeOut||scholar.bsrsTimeOut):(scholar.bsrsTimeOut||manualTimeOut);if(!finalTimeIn)errors.push("Time In is required to validate this attendance as present.");if(!finalTimeOut)errors.push("Time Out is required to validate this attendance as present.");const finalIssue=NEXUS_SAM.Modules.Allowance.Service.timeIssue(finalTimeIn,finalTimeOut);if(finalIssue)errors.push("The validated Time In/Time Out is still invalid. Check the supporting attendance record.");finalStatus=source==="APPROVED_BSRS_EXEMPTION"?"PRESENT_MANUAL_EXEMPTION":"PRESENT_BSRS_MANUAL";}if(errors.length)return {ok:false,errors};const row=NEXUS_SAM.Modules.Validation.Model.record({...input,batchId:report.batchId,scholarName:scholar.name,manualTimeIn,manualTimeOut,finalTimeIn,finalTimeOut,finalStatus,source});NEXUS_SAM.Modules.Validation.Repository.save(row);return {ok:true,row};}
 function clear(reportId,scholarNo){NEXUS_SAM.Modules.Validation.Repository.remove(reportId,scholarNo);}
 function summary(batchId){const all=NEXUS_SAM.Modules.Attendance.Repository.byBatch(batchId).flatMap(r=>r.scholars.map(s=>resolvedScholar(r,s)));const completeBsrs=all.filter(s=>s.attendanceStatus==="COMPLETE_BSRS"&&!s.timeIssue).length;const validatedManual=all.filter(s=>s.validationStatus==="VALIDATED"&&s.validation&&s.finalStatus!=="ABSENT").length;const absent=all.filter(s=>s.finalStatus==="ABSENT").length;const pending=all.filter(s=>s.validationStatus==="FOR_VALIDATION").length;return {records:all.length,completeBsrs,validatedManual,absent,pending,ready:all.length>0&&pending===0};}
 return Object.freeze({queue,save,clear,summary,resolvedScholar,getSource,issueFor});
})();